<a href="https://colab.research.google.com/github/ramrajv/Ramraj_Prayag_Kaggle/blob/main/Test/TelecomChurn_Test_05_Apr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Exploratory Data Analysis
### Load libraries

In [27]:
# Load libraries
import numpy as np
import pandas as pd

import datetime as dt

import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec
import seaborn as sns
sns.set(style="ticks")
%matplotlib inline

from scipy.stats import norm
from scipy import stats

import sklearn
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_curve, auc

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

import warnings
warnings.filterwarnings("ignore")

In [28]:
url = 'https://raw.githubusercontent.com/ramrajv/Ramraj_Prayag_Kaggle/main/test%20(1).csv'
test = pd.read_csv(url)

In [29]:
url = 'https://media.githubusercontent.com/media/ramrajv/Ramraj_Prayag_Kaggle/main/train.csv'
train = pd.read_csv(url)

### Check for unique values

In [30]:
df = train.copy()
#df_test = test.copy()

In [31]:
df.head().T

,0,1,2,3,4
id,0,1,2,3,4
circle_id,109,109,109,109,109
loc_og_t2o_mou,0.0,0.0,0.0,0.0,0.0
std_og_t2o_mou,0.0,0.0,0.0,0.0,0.0
loc_ic_t2o_mou,0.0,0.0,0.0,0.0,0.0
last_date_of_month_6,6/30/2014,6/30/2014,6/30/2014,6/30/2014,6/30/2014
last_date_of_month_7,7/31/2014,7/31/2014,7/31/2014,7/31/2014,7/31/2014
last_date_of_month_8,8/31/2014,8/31/2014,8/31/2014,8/31/2014,8/31/2014
arpu_6,31.277,0.0,60.806,156.362,240.708
arpu_7,87.009,122.787,103.176,205.26,128.191
arpu_8,7.527,42.953,0.0,111.095,101.565
onnet_mou_6,48.58,0.0,0.53,7.26,21.28
onnet_mou_7,124.38,0.0,15.93,16.01,4.83
onnet_mou_8,1.29,0.0,0.0,0.0,6.13
offnet_mou_6,32.24,0.0,53.99,68.76,56.99
offnet_mou_7,96.68,25.99,82.05,78.48,38.11
offnet_mou_8,2.33,30.89,0.0,50.23,9.63
roam_ic_mou_6,0.0,0.0,0.0,0.0,53.64
roam_ic_mou_7,0.0,0.0,0.0,0.0,0.0
roam_ic_mou_8,0.0,0.0,0.0,0.0,0.0
roam_og_mou_6,0.0,0.0,0.0,0.0,15.73
roam_og_mou_7,0.0,0.0,0.0,0.0,0.0
roam_og_mou_8,0.0,0.0,0.0,1.63,0.0
loc_og_t2t_mou_6,2.23,0.0,0.53,6.99,10.16
loc_og_t2t_mou_7,0.0,0.0,12.98,3.94,4.83
loc_og_t2t_mou_8,0.28,0.0,0.0,0.0,6.13
loc_og_t2m_mou_6,5.29,0.0,24.11,37.91,36.74
loc_og_t2m_mou_7,16.04,0.0,0.0,44.89,19.88
loc_og_t2m_mou_8,2.33,0.0,0.0,23.63,4.61
loc_og_t2f_mou_6,0.0,0.0,0.0,0.0,11.99
loc_og_t2f_mou_7,0.0,0.0,0.0,0.0,1.23
loc_og_t2f_mou_8,0.0,0.0,0.0,0.0,5.01
loc_og_t2c_mou_6,0.0,0.0,2.14,0.0,0.0
loc_og_t2c_mou_7,0.0,22.01,0.0,0.0,9.85
loc_og_t2c_mou_8,0.0,29.79,0.0,8.03,0.0
loc_og_mou_6,7.53,0.0,24.64,44.91,58.91
loc_og_mou_7,16.04,0.0,12.98,48.84,25.94
loc_og_mou_8,2.61,0.0,0.0,23.63,15.76
std_og_t2t_mou_6,46.34,0.0,0.0,0.26,0.0
std_og_t2t_mou_7,124.38,0.0,2.94,12.06,0.0
std_og_t2t_mou_8,1.01,0.0,0.0,0.0,0.0
std_og_t2m_mou_6,18.75,0.0,28.94,15.33,4.35
std_og_t2m_mou_7,80.61,0.0,82.05,25.93,0.0
std_og_t2m_mou_8,0.0,0.0,0.0,4.6,0.0
std_og_t2f_mou_6,0.0,0.0,0.0,0.56,0.0
std_og_t2f_mou_7,0.0,0.0,0.0,0.0,0.0
std_og_t2f_mou_8,0.0,0.0,0.0,0.0,0.0
std_og_t2c_mou_6,0.0,0.0,0.0,0.0,0.0
std_og_t2c_mou_7,0.0,0.0,0.0,0.0,0.0
std_og_t2c_mou_8,0.0,0.0,0.0,0.0,0.0
std_og_mou_6,65.09,0.0,28.94,16.16,4.35
std_og_mou_7,204.99,0.0,84.99,37.99,0.0
std_og_mou_8,1.01,0.0,0.0,4.6,0.0
isd_og_mou_6,0.0,0.0,0.0,0.0,0.0
isd_og_mou_7,0.0,0.0,0.0,0.0,0.0
isd_og_mou_8,0.0,0.0,0.0,0.0,0.0
spl_og_mou_6,8.2,0.0,2.89,14.95,0.0
spl_og_mou_7,0.63,30.73,1.38,9.13,17.0
spl_og_mou_8,0.0,31.66,0.0,25.61,0.0
og_others_6,0.38,0.0,0.0,0.0,0.0
og_others_7,0.0,0.0,0.0,0.0,0.0
og_others_8,0.0,0.0,0.0,0.0,0.0
total_og_mou_6,81.21,0.0,56.49,76.03,63.26
total_og_mou_7,221.68,30.73,99.36,95.98,42.94
total_og_mou_8,3.63,31.66,0.0,53.84,15.76
loc_ic_t2t_mou_6,2.43,1.68,4.51,24.98,5.44
loc_ic_t2t_mou_7,3.68,19.09,6.16,4.84,1.39
loc_ic_t2t_mou_8,7.79,10.53,6.49,23.88,2.66
loc_ic_t2m_mou_6,0.83,1.41,89.86,53.99,10.58
loc_ic_t2m_mou_7,21.08,18.68,25.18,44.23,4.33
loc_ic_t2m_mou_8,16.91,11.09,23.51,57.14,19.49
loc_ic_t2f_mou_6,0.0,0.35,0.0,7.23,5.51
loc_ic_t2f_mou_7,0.0,1.66,0.0,0.81,3.63
loc_ic_t2f_mou_8,0.0,3.4,0.0,0.0,6.14
loc_ic_mou_6,3.26,3.44,94.38,86.21,21.54
loc_ic_mou_7,24.76,39.44,31.34,49.89,9.36
loc_ic_mou_8,24.71,25.03,30.01,81.03,28.31
std_ic_t2t_mou_6,0.0,0.0,11.69,0.0,0.0
std_ic_t2t_mou_7,7.61,0.0,0.0,0.0,0.0
std_ic_t2t_mou_8,0.21,0.0,0.0,0.0,0.0
std_ic_t2m_mou_6,7.46,0.0,18.21,8.89,0.0
std_ic_t2m_mou_7,19.96,0.0,2.48,0.28,0.0
std_ic_t2m_mou_8,14.96,0.0,6.38,2.81,0.0
std_ic_t2f_mou_6,0.0,0.0,0.0,0.0,0.0
std_ic_t2f_mou_7,0.0,0.0,0.0,0.0,0.0
std_ic_t2f_mou_8,0.0,0.0,0.0,0.0,0.0
std_ic_t2o_mou_6,0.0,0.0,0.0,0.0,0.0
std_ic_t2o_mou_7,0.0,0.0,0.0,0.0,0.0
std_ic_t2o_mou_8,0.0,0.0,0.0,0.0,0.0
std_ic_mou_6,7.46,0.0,29.91,8.89,0.0
std_ic_mou_7,27.58,0.0,2.48,0.28,0.0
std_ic_mou_8,15.18,0.0,6.38,2.81,0.0
total_ic_mou_6,11.84,3.44,124.29,95.11,21.54
total_ic_mou_7,53.04,39.44,33.83,50.18,9.36
total_ic_mou_8,40.56,25.04,36.64,83.84,28.31
spl_ic_mou_6,0.0,0.0,0.0,0.0,0.0
spl_ic_mou_7,0.0,0.0,0.0,0.0,0.0
spl_ic_mou_8,0.66,0.01,0.0,0.0,0.0
isd_ic_mou_6,0.0,0.0,0.0,0.0,0.0
isd_ic_mou_7,0.0,0.0,0.0,0.0,0.0
isd_ic_mou_8,0.0,0.0,0.0,0.0,0.0
ic_others_6,1.11,0.0,0.0,0.0,0.0
ic_others_7,0.69,0.0,0.0,0.0,0.0
ic_others_8,0.0,0.0,0.25,0.0,0.0
total_rech_num_6,3,3,2,2,13
total_rech_num_7,2,4,4,4,10
total_rech_num_8,2,5,2,3,8
total_rech_amt_6,77,0,70,160,290
total_rech_amt_7,65,145,120,240,136
total_rech_amt_8,10,50,0,130,122
max_rech_amt_6,65,0,70,110,50
max_rech_amt_7,65,145,70,110,41
max_rech_amt_8,10,50,0,50,30
date_of_last_rech_6,6/22/2014,6/12/2014,6/11/2014,6/15/2014,6/25/2014
date_of_last_rech_7,7/10/2014,7/10/2014,7/22/2014,7/21/2014,7/26/2014
date_of_last_rech_8,8/24/2014,8/26/2014,8/24/2014,8/25/2014,8/30/2014
last_day_rch_amt_6,65,0,70,110,25
last_day_rch_amt_7,65,0,50,110,10
last_day_rch_amt_8,0,0,0,50,30
date_of_last_rech_data_6,NaN,NaN,NaN,NaN,6/25/2014
date_of_last_rech_data_7,NaN,7/8/2014,NaN,NaN,7/23/2014
date_of_last_rech_data_8,NaN,NaN,NaN,NaN,8/20/2014
total_rech_data_6,NaN,NaN,NaN,NaN,7.0
total_rech_data_7,NaN,1.0,NaN,NaN,7.0
total_rech_data_8,NaN,NaN,NaN,NaN,6.0
max_rech_data_6,NaN,NaN,NaN,NaN,25.0
max_rech_data_7,NaN,145.0,NaN,NaN,41.0
max_rech_data_8,NaN,NaN,NaN,NaN,25.0
count_rech_2g_6,NaN,NaN,NaN,NaN,7.0
count_rech_2g_7,NaN,0.0,NaN,NaN,6.0
count_rech_2g_8,NaN,NaN,NaN,NaN,6.0
count_rech_3g_6,NaN,NaN,NaN,NaN,0.0
count_rech_3g_7,NaN,1.0,NaN,NaN,1.0
count_rech_3g_8,NaN,NaN,NaN,NaN,0.0
av_rech_amt_data_6,NaN,NaN,NaN,NaN,175.0
av_rech_amt_data_7,NaN,145.0,NaN,NaN,191.0
av_rech_amt_data_8,NaN,NaN,NaN,NaN,142.0
vol_2g_mb_6,0.0,0.0,0.0,0.0,390.8
vol_2g_mb_7,0.0,352.91,0.0,0.0,308.89
vol_2g_mb_8,0.0,0.0,0.0,0.0,213.47
vol_3g_mb_6,0.0,0.0,0.0,0.0,0.0
vol_3g_mb_7,0.0,3.96,0.0,0.0,0.0
vol_3g_mb_8,0.0,0.0,0.0,0.0,0.0
arpu_3g_6,NaN,NaN,NaN,NaN,0.0
arpu_3g_7,NaN,122.07,NaN,NaN,35.0
arpu_3g_8,NaN,NaN,NaN,NaN,0.0
arpu_2g_6,NaN,NaN,NaN,NaN,0.0
arpu_2g_7,NaN,122.08,NaN,NaN,35.12
arpu_2g_8,NaN,NaN,NaN,NaN,0.0
night_pck_user_6,NaN,NaN,NaN,NaN,0.0
night_pck_user_7,NaN,0.0,NaN,NaN,0.0
night_pck_user_8,NaN,NaN,NaN,NaN,0.0
monthly_2g_6,0,0,0,0,0
monthly_2g_7,0,0,0,0,0
monthly_2g_8,0,0,0,0,0
sachet_2g_6,0,0,0,0,7
sachet_2g_7,0,0,0,0,6
sachet_2g_8,0,0,0,0,6
monthly_3g_6,0,0,0,0,0
monthly_3g_7,0,1,0,0,0
monthly_3g_8,0,0,0,0,0
sachet_3g_6,0,0,0,0,0
sachet_3g_7,0,0,0,0,1
sachet_3g_8,0,0,0,0,0
fb_user_6,NaN,NaN,NaN,NaN,1.0
fb_user_7,NaN,1.0,NaN,NaN,1.0
fb_user_8,NaN,NaN,NaN,NaN,1.0
aon,1958,710,882,982,647
aug_vbc_3g,0.0,0.0,0.0,0.0,0.0
jul_vbc_3g,0.0,0.0,0.0,0.0,0.0
jun_vbc_3g,0.0,0.0,0.0,0.0,0.0
churn_probability,0,0,0,0,0

In [32]:
df.shape

(69999, 172)

In [33]:
dfx = df.drop(['id','churn_probability'], axis = 1)
#dfxt = df_test.drop('id', axis = 1)

In [34]:
dfx.columns[dfx.isna().sum()/dfx.shape[0]>0]

Index(['loc_og_t2o_mou', 'std_og_t2o_mou', 'loc_ic_t2o_mou',
       'last_date_of_month_7', 'last_date_of_month_8', 'onnet_mou_6',
       'onnet_mou_7', 'onnet_mou_8', 'offnet_mou_6', 'offnet_mou_7',
       ...
       'arpu_3g_8', 'arpu_2g_6', 'arpu_2g_7', 'arpu_2g_8', 'night_pck_user_6',
       'night_pck_user_7', 'night_pck_user_8', 'fb_user_6', 'fb_user_7',
       'fb_user_8'],
      dtype='object', length=125)

### Drop null data

#### Drop rows with all null values

In [35]:
dfx.dropna(how = 'all', inplace = True)
#dfxt.dropna(how = 'all', inplace = True)

In [36]:
dfx.shape

(69999, 170)

In [37]:
dfx.sample(5).T

,7933,36591,62204,18934,29922
circle_id,109,109,109,109,109
loc_og_t2o_mou,0.0,0.0,0.0,0.0,0.0
std_og_t2o_mou,0.0,0.0,0.0,0.0,0.0
loc_ic_t2o_mou,0.0,0.0,0.0,0.0,0.0
last_date_of_month_6,6/30/2014,6/30/2014,6/30/2014,6/30/2014,6/30/2014
last_date_of_month_7,7/31/2014,7/31/2014,7/31/2014,7/31/2014,7/31/2014
last_date_of_month_8,8/31/2014,8/31/2014,8/31/2014,8/31/2014,8/31/2014
arpu_6,162.799,90.449,269.869,1077.042,349.953
arpu_7,78.787,31.406,76.706,944.457,181.418
arpu_8,297.172,42.98,136.549,991.065,146.416
onnet_mou_6,56.29,28.06,84.03,396.21,150.61
onnet_mou_7,23.33,20.44,10.04,321.88,207.91
onnet_mou_8,179.56,21.08,15.79,307.54,208.66
offnet_mou_6,111.59,29.18,101.34,1200.64,146.23
offnet_mou_7,81.81,18.13,70.94,1140.38,152.96
offnet_mou_8,152.78,7.81,67.54,1137.54,94.99
roam_ic_mou_6,0.0,0.0,0.0,0.0,0.0
roam_ic_mou_7,0.0,0.0,0.0,0.0,0.0
roam_ic_mou_8,0.0,0.0,0.0,0.0,0.0
roam_og_mou_6,0.0,0.0,0.0,0.0,0.0
roam_og_mou_7,0.0,0.0,0.0,0.0,0.0
roam_og_mou_8,0.0,0.0,0.0,0.0,0.0
loc_og_t2t_mou_6,0.41,28.06,16.66,215.86,38.76
loc_og_t2t_mou_7,0.0,20.44,3.71,134.84,7.24
loc_og_t2t_mou_8,2.35,18.53,5.51,166.36,9.24
loc_og_t2m_mou_6,9.51,28.89,90.19,634.48,68.96
loc_og_t2m_mou_7,30.13,16.24,50.04,626.36,117.61
loc_og_t2m_mou_8,23.23,7.81,35.31,595.61,77.26
loc_og_t2f_mou_6,0.56,0.0,0.0,57.53,0.21
loc_og_t2f_mou_7,1.65,0.0,0.0,18.39,0.0
loc_og_t2f_mou_8,6.11,0.0,0.0,13.64,0.0
loc_og_t2c_mou_6,0.0,0.0,0.0,0.0,0.0
loc_og_t2c_mou_7,0.0,1.88,0.0,0.0,0.0
loc_og_t2c_mou_8,0.0,0.0,0.0,0.0,0.0
loc_og_mou_6,10.49,56.96,106.86,907.88,107.94
loc_og_mou_7,31.78,36.69,53.76,779.61,124.86
loc_og_mou_8,31.69,26.34,40.83,775.63,86.51
std_og_t2t_mou_6,55.88,0.0,67.36,180.34,111.84
std_og_t2t_mou_7,23.33,0.0,6.33,187.03,200.66
std_og_t2t_mou_8,177.21,2.54,10.28,141.18,199.41
std_og_t2m_mou_6,101.51,0.28,11.14,508.63,35.03
std_og_t2m_mou_7,50.03,0.0,20.89,495.36,19.08
std_og_t2m_mou_8,117.31,0.0,32.23,528.28,17.03
std_og_t2f_mou_6,0.0,0.0,0.0,0.0,42.01
std_og_t2f_mou_7,0.0,0.0,0.0,0.25,16.26
std_og_t2f_mou_8,6.11,0.0,0.0,0.0,0.7
std_og_t2c_mou_6,0.0,0.0,0.0,0.0,0.0
std_og_t2c_mou_7,0.0,0.0,0.0,0.0,0.0
std_og_t2c_mou_8,0.0,0.0,0.0,0.0,0.0
std_og_mou_6,157.39,0.28,78.51,688.98,188.89
std_og_mou_7,73.36,0.0,27.23,682.64,236.01
std_og_mou_8,300.64,2.54,42.51,669.46,217.14
isd_og_mou_6,0.0,0.0,0.0,0.0,0.0
isd_og_mou_7,0.0,0.0,0.0,0.0,0.0
isd_og_mou_8,0.0,0.0,0.0,0.0,0.0
spl_og_mou_6,0.0,0.0,0.63,0.0,0.0
spl_og_mou_7,0.0,1.88,0.0,0.0,0.0
spl_og_mou_8,0.0,0.0,6.19,0.0,0.0
og_others_6,0.0,0.0,0.0,0.0,0.0
og_others_7,0.0,0.0,0.0,0.0,0.0
og_others_8,0.0,0.0,0.0,0.0,0.0
total_og_mou_6,167.89,57.24,186.01,1596.86,296.84
total_og_mou_7,105.14,38.58,80.99,1462.26,360.88
total_og_mou_8,332.34,28.89,89.54,1445.09,303.66
loc_ic_t2t_mou_6,0.43,49.59,29.94,354.91,7.09
loc_ic_t2t_mou_7,3.51,16.54,21.74,284.79,11.86
loc_ic_t2t_mou_8,0.36,9.61,22.28,313.19,8.94
loc_ic_t2m_mou_6,6.81,39.64,96.21,672.48,94.34
loc_ic_t2m_mou_7,24.39,10.03,122.66,659.64,73.83
loc_ic_t2m_mou_8,20.34,26.73,105.54,641.84,88.43
loc_ic_t2f_mou_6,3.86,0.0,0.0,59.78,8.21
loc_ic_t2f_mou_7,8.08,0.0,0.0,64.48,10.89
loc_ic_t2f_mou_8,8.59,0.0,0.0,47.01,1.64
loc_ic_mou_6,11.11,89.24,126.16,1087.18,109.66
loc_ic_mou_7,35.99,26.58,144.41,1008.93,96.59
loc_ic_mou_8,29.31,36.34,127.83,1002.06,99.03
std_ic_t2t_mou_6,17.33,2.56,6.56,113.44,9.29
std_ic_t2t_mou_7,1.3,0.0,11.61,130.43,17.89
std_ic_t2t_mou_8,7.48,0.0,2.24,69.26,0.13
std_ic_t2m_mou_6,3.36,0.0,1.53,459.59,2.18
std_ic_t2m_mou_7,13.36,3.38,4.83,437.91,35.1
std_ic_t2m_mou_8,6.73,0.0,14.13,535.98,0.0
std_ic_t2f_mou_6,0.0,0.0,0.0,0.83,0.0
std_ic_t2f_mou_7,0.0,0.0,0.0,2.61,0.0
std_ic_t2f_mou_8,0.0,0.0,0.0,2.91,6.35
std_ic_t2o_mou_6,0.0,0.0,0.0,0.0,0.0
std_ic_t2o_mou_7,0.0,0.0,0.0,0.0,0.0
std_ic_t2o_mou_8,0.0,0.0,0.0,0.0,0.0
std_ic_mou_6,20.69,2.56,8.09,573.88,11.48
std_ic_mou_7,14.66,3.38,16.44,570.96,52.99
std_ic_mou_8,14.21,0.0,16.38,608.16,6.48
total_ic_mou_6,31.81,91.81,134.26,1661.06,121.19
total_ic_mou_7,50.66,29.96,160.86,1579.89,149.59
total_ic_mou_8,43.73,36.34,144.21,1610.23,105.51
spl_ic_mou_6,0.0,0.0,0.0,0.0,0.05
spl_ic_mou_7,0.0,0.0,0.0,0.0,0.0
spl_ic_mou_8,0.0,0.0,0.0,0.0,0.0
isd_ic_mou_6,0.0,0.0,0.0,0.0,0.0
isd_ic_mou_7,0.0,0.0,0.0,0.0,0.0
isd_ic_mou_8,0.0,0.0,0.0,0.0,0.0
ic_others_6,0.0,0.0,0.0,0.0,0.0
ic_others_7,0.0,0.0,0.0,0.0,0.0
ic_others_8,0.2,0.0,0.0,0.0,0.0
total_rech_num_6,3,6,2,9,5
total_rech_num_7,3,3,2,5,4
total_rech_num_8,2,3,1,6,2
total_rech_amt_6,140,120,240,1463,302
total_rech_amt_7,240,88,240,1084,297
total_rech_amt_8,260,0,50,1084,144
max_rech_amt_6,70,30,120,339,128
max_rech_amt_7,130,44,120,339,169
max_rech_amt_8,130,0,50,339,144
date_of_last_rech_6,6/25/2014,6/26/2014,6/17/2014,6/28/2014,6/24/2014
date_of_last_rech_7,7/31/2014,7/25/2014,7/25/2014,7/27/2014,7/11/2014
date_of_last_rech_8,8/26/2014,8/24/2014,8/21/2014,8/26/2014,8/28/2014
last_day_rch_amt_6,70,30,120,339,50
last_day_rch_amt_7,130,44,120,339,169
last_day_rch_amt_8,130,0,50,339,0
date_of_last_rech_data_6,NaN,NaN,NaN,6/12/2014,6/19/2014
date_of_last_rech_data_7,NaN,NaN,NaN,7/11/2014,NaN
date_of_last_rech_data_8,NaN,NaN,NaN,8/8/2014,NaN
total_rech_data_6,NaN,NaN,NaN,1.0,1.0
total_rech_data_7,NaN,NaN,NaN,1.0,NaN
total_rech_data_8,NaN,NaN,NaN,1.0,NaN
max_rech_data_6,NaN,NaN,NaN,25.0,25.0
max_rech_data_7,NaN,NaN,NaN,25.0,NaN
max_rech_data_8,NaN,NaN,NaN,25.0,NaN
count_rech_2g_6,NaN,NaN,NaN,1.0,1.0
count_rech_2g_7,NaN,NaN,NaN,1.0,NaN
count_rech_2g_8,NaN,NaN,NaN,1.0,NaN
count_rech_3g_6,NaN,NaN,NaN,0.0,0.0
count_rech_3g_7,NaN,NaN,NaN,0.0,NaN
count_rech_3g_8,NaN,NaN,NaN,0.0,NaN
av_rech_amt_data_6,NaN,NaN,NaN,25.0,25.0
av_rech_amt_data_7,NaN,NaN,NaN,25.0,NaN
av_rech_amt_data_8,NaN,NaN,NaN,25.0,NaN
vol_2g_mb_6,0.0,0.0,0.0,0.0,0.0
vol_2g_mb_7,0.0,0.0,0.0,0.0,0.0
vol_2g_mb_8,0.0,0.0,0.0,0.0,0.0
vol_3g_mb_6,0.0,0.0,0.0,0.0,34.45
vol_3g_mb_7,0.0,0.0,0.0,0.0,0.0
vol_3g_mb_8,0.0,0.0,0.0,0.0,0.0
arpu_3g_6,NaN,NaN,NaN,0.0,0.0
arpu_3g_7,NaN,NaN,NaN,0.0,NaN
arpu_3g_8,NaN,NaN,NaN,0.0,NaN
arpu_2g_6,NaN,NaN,NaN,0.0,0.0
arpu_2g_7,NaN,NaN,NaN,0.0,NaN
arpu_2g_8,NaN,NaN,NaN,0.0,NaN
night_pck_user_6,NaN,NaN,NaN,0.0,0.0
night_pck_user_7,NaN,NaN,NaN,0.0,NaN
night_pck_user_8,NaN,NaN,NaN,0.0,NaN
monthly_2g_6,0,0,0,0,0
monthly_2g_7,0,0,0,0,0
monthly_2g_8,0,0,0,0,0
sachet_2g_6,0,0,0,1,1
sachet_2g_7,0,0,0,1,0
sachet_2g_8,0,0,0,1,0
monthly_3g_6,0,0,0,0,0
monthly_3g_7,0,0,0,0,0
monthly_3g_8,0,0,0,0,0
sachet_3g_6,0,0,0,0,0
sachet_3g_7,0,0,0,0,0
sachet_3g_8,0,0,0,0,0
fb_user_6,NaN,NaN,NaN,0.0,1.0
fb_user_7,NaN,NaN,NaN,0.0,NaN
fb_user_8,NaN,NaN,NaN,0.0,NaN
aon,1292,1718,1193,2712,361
aug_vbc_3g,0.0,0.0,0.0,0.0,0.0
jul_vbc_3g,0.0,0.0,0.0,0.0,0.0
jun_vbc_3g,0.0,0.0,0.0,0.0,0.0

#### Drop columns with null values in more than 70% of the rows

In [38]:
drop_cols = dfx.columns[dfx.isna().sum()/dfx.shape[0]>0.7]
#drop_colst = dfxt.columns[dfxt.isna().sum()/dfxt.shape[0]>0.7]

In [39]:
drop_cols

Index(['date_of_last_rech_data_6', 'date_of_last_rech_data_7',
       'date_of_last_rech_data_8', 'total_rech_data_6', 'total_rech_data_7',
       'total_rech_data_8', 'max_rech_data_6', 'max_rech_data_7',
       'max_rech_data_8', 'count_rech_2g_6', 'count_rech_2g_7',
       'count_rech_2g_8', 'count_rech_3g_6', 'count_rech_3g_7',
       'count_rech_3g_8', 'av_rech_amt_data_6', 'av_rech_amt_data_7',
       'av_rech_amt_data_8', 'arpu_3g_6', 'arpu_3g_7', 'arpu_3g_8',
       'arpu_2g_6', 'arpu_2g_7', 'arpu_2g_8', 'night_pck_user_6',
       'night_pck_user_7', 'night_pck_user_8', 'fb_user_6', 'fb_user_7',
       'fb_user_8'],
      dtype='object')

In [40]:
len(drop_cols)

30

In [41]:
df.head()

,id,circle_id,loc_og_t2o_mou,std_og_t2o_mou,loc_ic_t2o_mou,last_date_of_month_6,last_date_of_month_7,last_date_of_month_8,arpu_6,arpu_7,arpu_8,onnet_mou_6,onnet_mou_7,onnet_mou_8,offnet_mou_6,offnet_mou_7,offnet_mou_8,roam_ic_mou_6,roam_ic_mou_7,roam_ic_mou_8,roam_og_mou_6,roam_og_mou_7,roam_og_mou_8,loc_og_t2t_mou_6,loc_og_t2t_mou_7,loc_og_t2t_mou_8,loc_og_t2m_mou_6,loc_og_t2m_mou_7,loc_og_t2m_mou_8,loc_og_t2f_mou_6,loc_og_t2f_mou_7,loc_og_t2f_mou_8,loc_og_t2c_mou_6,loc_og_t2c_mou_7,loc_og_t2c_mou_8,loc_og_mou_6,loc_og_mou_7,loc_og_mou_8,std_og_t2t_mou_6,std_og_t2t_mou_7,std_og_t2t_mou_8,std_og_t2m_mou_6,std_og_t2m_mou_7,std_og_t2m_mou_8,std_og_t2f_mou_6,std_og_t2f_mou_7,std_og_t2f_mou_8,std_og_t2c_mou_6,std_og_t2c_mou_7,std_og_t2c_mou_8,std_og_mou_6,std_og_mou_7,std_og_mou_8,isd_og_mou_6,isd_og_mou_7,isd_og_mou_8,spl_og_mou_6,spl_og_mou_7,spl_og_mou_8,og_others_6,og_others_7,og_others_8,total_og_mou_6,total_og_mou_7,total_og_mou_8,loc_ic_t2t_mou_6,loc_ic_t2t_mou_7,loc_ic_t2t_mou_8,loc_ic_t2m_mou_6,loc_ic_t2m_mou_7,loc_ic_t2m_mou_8,loc_ic_t2f_mou_6,loc_ic_t2f_mou_7,loc_ic_t2f_mou_8,loc_ic_mou_6,loc_ic_mou_7,loc_ic_mou_8,std_ic_t2t_mou_6,std_ic_t2t_mou_7,std_ic_t2t_mou_8,std_ic_t2m_mou_6,std_ic_t2m_mou_7,std_ic_t2m_mou_8,std_ic_t2f_mou_6,std_ic_t2f_mou_7,std_ic_t2f_mou_8,std_ic_t2o_mou_6,std_ic_t2o_mou_7,std_ic_t2o_mou_8,std_ic_mou_6,std_ic_mou_7,std_ic_mou_8,total_ic_mou_6,total_ic_mou_7,total_ic_mou_8,spl_ic_mou_6,spl_ic_mou_7,spl_ic_mou_8,isd_ic_mou_6,isd_ic_mou_7,isd_ic_mou_8,ic_others_6,ic_others_7,ic_others_8,total_rech_num_6,total_rech_num_7,total_rech_num_8,total_rech_amt_6,total_rech_amt_7,total_rech_amt_8,max_rech_amt_6,max_rech_amt_7,max_rech_amt_8,date_of_last_rech_6,date_of_last_rech_7,date_of_last_rech_8,last_day_rch_amt_6,last_day_rch_amt_7,last_day_rch_amt_8,date_of_last_rech_data_6,date_of_last_rech_data_7,date_of_last_rech_data_8,total_rech_data_6,total_rech_data_7,total_rech_data_8,max_rech_data_6,max_rech_data_7,max_rech_data_8,count_rech_2g_6,count_rech_2g_7,count_rech_2g_8,count_rech_3g_6,count_rech_3g_7,count_rech_3g_8,av_rech_amt_data_6,av_rech_amt_data_7,av_rech_amt_data_8,vol_2g_mb_6,vol_2g_mb_7,vol_2g_mb_8,vol_3g_mb_6,vol_3g_mb_7,vol_3g_mb_8,arpu_3g_6,arpu_3g_7,arpu_3g_8,arpu_2g_6,arpu_2g_7,arpu_2g_8,night_pck_user_6,night_pck_user_7,night_pck_user_8,monthly_2g_6,monthly_2g_7,monthly_2g_8,sachet_2g_6,sachet_2g_7,sachet_2g_8,monthly_3g_6,monthly_3g_7,monthly_3g_8,sachet_3g_6,sachet_3g_7,sachet_3g_8,fb_user_6,fb_user_7,fb_user_8,aon,aug_vbc_3g,jul_vbc_3g,jun_vbc_3g,churn_probability
0,0,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,31.277,87.009,7.527,48.58,124.38,1.29,32.24,96.68,2.33,0.00,0.0,0.0,0.00,0.0,0.00,2.23,0.00,0.28,5.29,16.04,2.33,0.00,0.00,0.00,0.00,0.00,0.00,7.53,16.04,2.61,46.34,124.38,1.01,18.75,80.61,0.0,0.00,0.0,0.0,0.0,0.0,0.0,65.09,204.99,1.01,0.0,0.0,0.0,8.20,0.63,0.00,0.38,0.0,0.0,81.21,221.68,3.63,2.43,3.68,7.79,0.83,21.08,16.91,0.00,0.00,0.00,3.26,24.76,24.71,0.00,7.61,0.21,7.46,19.96,14.96,0.0,0.0,0.0,0.0,0.0,0.0,7.46,27.58,15.18,11.84,53.04,40.56,0.0,0.0,0.66,0.0,0.0,0.0,1.11,0.69,0.00,3,2,2,77,65,10,65,65,10,6/22/2014,7/10/2014,8/24/2014,65,65,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.00,0.00,0.0,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,1958,0.0,0.0,0.0,0
1,1,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,0.000,122.787,42.953,0.00,0.00,0.00,0.00,25.99,30.89,0.00,0.0,0.0,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,22.01,29.79,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,30.73,31.66,0.00,0.0,0.0,0.00,30.73,31.66,1.68,19.09,10.53,1.41,18.68,11.09,0.35,1.66,3.40,3.44,39.44,25.03,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,3.44,39.44,25.04,0.0,0.0,0.01,0.0,0.0,0.0,0.00,0.00,0.00,3,4,5,0,145,50,0,145,50,6/12/2014,7/10/2014,8/26/2014,0,0,0,NaN,7/8/2014,NaN,NaN,1.0,NaN,NaN,145.0,NaN,NaN,0.0,NaN,NaN,1.0,NaN,NaN,145.0,NaN,0.0,352.91,0.00,0.0,3.96,0.0,NaN,122.07,NaN,NaN,122.08,NaN,NaN,0.0,NaN,0,0,0,0,0,0,0,1,0,0,0,0,NaN,1.0,NaN,710,0.0,0.0,0.0,0
2,2,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,60.806,103.176,0.000,0.53,15.93,0.00,53.99,82.05,0.00,0.00,0.0,0.0,0.00,0.0,0.00,0.53,12.98,0.00,24.11,0.00,0.00,0.00,0.00,0.00,2.14,0.00,0.00,24.64,12.98,0.00,0.00,2.94,0.00,28.94,82.05,0.0,0.00,0.0,0.0,0.0,0.0,0.0,28.94,84.99,0.00,0.0,0.0,0.0,2.89,1.38,0.00,0.00,0.0,0.0,56.49,99.36,0.00,4.51,6.16,6.49,89.86,25.18,23.51,0.00,0.00,0.00,94.38,31.34,30.01,11.69,0.00,0.00,18.21,2.48,6.38,0.0,0.0,0.0,0.0,0.0,0.0,29.91,2.48,6.38,124.29,33.83,36.64,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.00,0.25,2,4,2,70,120,0,70,70,0,6/11/2014,7/22/2014,8/24/2014,70,50,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.00,0.00,0.0,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,882,0.0,0.0,0.0,0
3,3,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,156.362,205.260,111.095,7.26,16.01,0.00,68.76,78.48,50.23,0.00,0.0,0.0,0.00,0.0,1.63,6.99,3.94,0.00,37.91,44.89,23.63,0.00,0.00,0.00,0.00,0.00,8.03,44.91,48.84,23.63,0.26,12.06,0.00,15.33,25.93,4.6,0.56,0.0,0.0,0.0,0.0,0.0,16.16,37.99,4.60,0.0,0.0,0.0,14.95,9.13,25.61,0.00,0.0,0.0,76.03,95.98,53.84,24.98,4.84,23.88,53.99,44.23,57.14,7.23,0.81,0.00,86.21,49.89,81.03,0.00,0.00,0.00,8.89,0.28,2.81,0.0,0.0,0.0,0.0,0.0,0.0,8.89,0.28,2.81,95.11,50.18,83.84,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.00,0.00,2,4,3,160,240,130,110,110,50,6/15/2014,7/21/2014,8/25/2014,110,110,50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.00,0.00,0.0,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,982,0.0,0.0,0.0,0
4,4,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,240.708,128.191,101.565,21.28,4.83,6.13,56.99,38.11,9.63,53.64,0.0,0.0,15.73,0.0,0.00,10.16,4.83,6.13,36.74,19.88,4.61,11.99,1.23,5.01,0.00,9.85,0.00,58.91,25.94,15.76,0.00,0.00,0.00,4.35,0.00,0.0,0.00,0.0,0.0,0.0,0.0,0.0,4.35,0.00,0.00,0.0,0.0,0.0,0.00,17.00,0.00,0.00,0.0,0.0,63.26,42.94,15.76,5.44,1.39,2.66,10.58,4.33,19.49,5.51,3.63,6.14,21.54,9.36,28.31,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,21.54,9.36,28.31,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.00,0.00,13,10,8,290,136,122,50,41,30,6/25/2014,7/26/2014,8/30/2014,25,10,30,6/25/2014,7/23/2014,8/20/2014,7.0,7.0,6.0,25.0,41.0,25.0,7.0,6.0,6.0,0.0,1.0,0.0,175.0,191.0,142.0,390.8,308.89,213.47,0.0,0.00,0.0,0.0,35.00,0.0,0.0,35.12,0.0,0.0,0.0,0.0,0,0,0,7,6,6,0,0,0,0,1,0,1.0,1.0,1.0,647,0.0,0.0,0.0,0

In [69]:
dfx.groupby('churn_probability')[drop_cols].count().T

KeyError: ignored

In [70]:
dfx[drop_cols].sample(5).T

                         37547      59606 61000 58380      8397
date_of_last_rech_data_6   NaN  6/30/2014   NaN   NaN  6/10/2014
date_of_last_rech_data_7   NaN  7/27/2014   NaN   NaN  7/24/2014
date_of_last_rech_data_8   NaN  8/19/2014   NaN   NaN  8/11/2014
total_rech_data_6          NaN        1.0   NaN   NaN        1.0
total_rech_data_7          NaN        3.0   NaN   NaN        1.0
total_rech_data_8          NaN        4.0   NaN   NaN        1.0
max_rech_data_6            NaN       14.0   NaN   NaN      154.0
max_rech_data_7            NaN       14.0   NaN   NaN      154.0
max_rech_data_8            NaN       25.0   NaN   NaN      154.0
count_rech_2g_6            NaN        1.0   NaN   NaN        1.0
count_rech_2g_7            NaN        3.0   NaN   NaN        1.0
count_rech_2g_8            NaN        4.0   NaN   NaN        1.0
count_rech_3g_6            NaN        0.0   NaN   NaN        0.0
count_rech_3g_7            NaN        0.0   NaN   NaN        0.0
count_rech_3g_8            NaN        0.0   NaN   NaN        0.0
av_rech_amt_data_6         NaN       14.0   NaN   NaN      154.0
av_rech_amt_data_7         NaN       42.0   NaN   NaN      154.0
av_rech_amt_data_8         NaN       84.0   NaN   NaN      154.0
arpu_3g_6                  NaN        0.0   NaN   NaN     243.25
arpu_3g_7                  NaN        0.0   NaN   NaN     304.92
arpu_3g_8                  NaN        0.0   NaN   NaN       0.01
arpu_2g_6                  NaN        0.0   NaN   NaN        0.0
arpu_2g_7                  NaN        0.0   NaN   NaN      76.25
arpu_2g_8                  NaN       12.7   NaN   NaN        0.0
night_pck_user_6           NaN        0.0   NaN   NaN        0.0
night_pck_user_7           NaN        0.0   NaN   NaN        0.0
night_pck_user_8           NaN        0.0   NaN   NaN        0.0
fb_user_6                  NaN        1.0   NaN   NaN        1.0
fb_user_7                  NaN        1.0   NaN   NaN        1.0
fb_user_8                  NaN        1.0   NaN   NaN        1.0

In [71]:
dfx[dfx[drop_cols]==0][drop_cols].sample(5).T

                         22920 68994 20289 69508 18935
date_of_last_rech_data_6   NaN   NaN   NaN   NaN   NaN
date_of_last_rech_data_7   NaN   NaN   NaN   NaN   NaN
date_of_last_rech_data_8   NaN   NaN   NaN   NaN   NaN
total_rech_data_6          NaN   NaN   NaN   NaN   NaN
total_rech_data_7          NaN   NaN   NaN   NaN   NaN
total_rech_data_8          NaN   NaN   NaN   NaN   NaN
max_rech_data_6            NaN   NaN   NaN   NaN   NaN
max_rech_data_7            NaN   NaN   NaN   NaN   NaN
max_rech_data_8            NaN   NaN   NaN   NaN   NaN
count_rech_2g_6            0.0   NaN   NaN   NaN   NaN
count_rech_2g_7            0.0   NaN   NaN   NaN   NaN
count_rech_2g_8            NaN   NaN   NaN   NaN   NaN
count_rech_3g_6            NaN   NaN   0.0   NaN   NaN
count_rech_3g_7            NaN   NaN   NaN   NaN   NaN
count_rech_3g_8            0.0   NaN   0.0   NaN   NaN
av_rech_amt_data_6         NaN   NaN   NaN   NaN   NaN
av_rech_amt_data_7         NaN   NaN   NaN   NaN   NaN
av_rech_amt_data_8         NaN   NaN   NaN   NaN   NaN
arpu_3g_6                  NaN   NaN   0.0   NaN   NaN
arpu_3g_7                  NaN   NaN   NaN   NaN   NaN
arpu_3g_8                  NaN   NaN   0.0   NaN   NaN
arpu_2g_6                  NaN   NaN   0.0   NaN   NaN
arpu_2g_7                  NaN   NaN   NaN   NaN   NaN
arpu_2g_8                  0.0   NaN   0.0   NaN   NaN
night_pck_user_6           0.0   NaN   0.0   NaN   NaN
night_pck_user_7           0.0   NaN   NaN   NaN   NaN
night_pck_user_8           0.0   NaN   0.0   NaN   NaN
fb_user_6                  NaN   NaN   NaN   NaN   NaN
fb_user_7                  NaN   NaN   NaN   NaN   NaN
fb_user_8                  NaN   NaN   NaN   NaN   NaN

In [72]:
dfx[drop_cols].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 69999 entries, 0 to 69998
Data columns (total 30 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   date_of_last_rech_data_6  17568 non-null  object
 1   date_of_last_rech_data_7  17865 non-null  object
 2   date_of_last_rech_data_8  18417 non-null  object
 3   total_rech_data_6         17568 non-null  float64
 4   total_rech_data_7         17865 non-null  float64
 5   total_rech_data_8         18417 non-null  float64
 6   max_rech_data_6           17568 non-null  float64
 7   max_rech_data_7           17865 non-null  float64
 8   max_rech_data_8           18417 non-null  float64
 9   count_rech_2g_6           17568 non-null  float64
 10  count_rech_2g_7           17865 non-null  float64
 11  count_rech_2g_8           18417 non-null  float64
 12  count_rech_3g_6           17568 non-null  float64
 13  count_rech_3g_7           17865 non-null  float64
 14  count_rech_3g_8           18417 non-null  float64
 15  av_rech_amt_data_6        17568 non-null  float64
 16  av_rech_amt_data_7        17865 non-null  float64
 17  av_rech_amt_data_8        18417 non-null  float64
 18  arpu_3g_6                 17568 non-null  float64
 19  arpu_3g_7                 17865 non-null  float64
 20  arpu_3g_8                 18417 non-null  float64
 21  arpu_2g_6                 17568 non-null  float64
 22  arpu_2g_7                 17865 non-null  float64
 23  arpu_2g_8                 18417 non-null  float64
 24  night_pck_user_6          17568 non-null  float64
 25  night_pck_user_7          17865 non-null  float64
 26  night_pck_user_8          18417 non-null  float64
 27  fb_user_6                 17568 non-null  float64
 28  fb_user_7                 17865 non-null  float64
 29  fb_user_8                 18417 non-null  float64
dtypes: float64(27), object(3)
memory usage: 16.6+ MB

In [73]:
# Check object types in dataframe

obj = dfx.columns[dfx.dtypes=='O']
obj

Index(['last_date_of_month_6', 'last_date_of_month_7', 'last_date_of_month_8',
       'date_of_last_rech_6', 'date_of_last_rech_7', 'date_of_last_rech_8',
       'date_of_last_rech_data_6', 'date_of_last_rech_data_7',
       'date_of_last_rech_data_8'],
      dtype='object')

In [74]:
dfx[obj].sample()

,last_date_of_month_6,last_date_of_month_7,last_date_of_month_8,date_of_last_rech_6,date_of_last_rech_7,date_of_last_rech_8,date_of_last_rech_data_6,date_of_last_rech_data_7,date_of_last_rech_data_8
10660,6/30/2014,7/31/2014,8/31/2014,6/27/2014,7/30/2014,8/25/2014,NaN,NaN,NaN

In [75]:
# Get difference between date of recharges and last date of months.

dfx['date_of_last_rech_6'] = (pd.to_datetime(dfx['last_date_of_month_6']) - pd.to_datetime(dfx['date_of_last_rech_6'])).dt.days

In [59]:
dfx['date_of_last_rech_7'] = (pd.to_datetime(dfx['last_date_of_month_7']) - pd.to_datetime(dfx['date_of_last_rech_7'])).dt.days
dfx['date_of_last_rech_8'] = (pd.to_datetime(dfx['last_date_of_month_8']) - pd.to_datetime(dfx['date_of_last_rech_8'])).dt.days

In [76]:
dfx['date_of_last_rech_data_7'] = (pd.to_datetime(dfx['last_date_of_month_7']) - pd.to_datetime(dfx['date_of_last_rech_data_7'])).dt.days
dfx['date_of_last_rech_data_8'] = (pd.to_datetime(dfx['last_date_of_month_8']) - pd.to_datetime(dfx['date_of_last_rech_data_8'])).dt.days
dfx['date_of_last_rech_data_6'] = (pd.to_datetime(dfx['last_date_of_month_6']) - pd.to_datetime(dfx['date_of_last_rech_6'])).dt.days

In [77]:
dfx[drop_cols].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 69999 entries, 0 to 69998
Data columns (total 30 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   date_of_last_rech_data_6  68898 non-null  float64
 1   date_of_last_rech_data_7  17865 non-null  float64
 2   date_of_last_rech_data_8  18417 non-null  float64
 3   total_rech_data_6         17568 non-null  float64
 4   total_rech_data_7         17865 non-null  float64
 5   total_rech_data_8         18417 non-null  float64
 6   max_rech_data_6           17568 non-null  float64
 7   max_rech_data_7           17865 non-null  float64
 8   max_rech_data_8           18417 non-null  float64
 9   count_rech_2g_6           17568 non-null  float64
 10  count_rech_2g_7           17865 non-null  float64
 11  count_rech_2g_8           18417 non-null  float64
 12  count_rech_3g_6           17568 non-null  float64
 13  count_rech_3g_7           17865 non-null  float64
 14  count_rech_3g_8           18417 non-null  float64
 15  av_rech_amt_data_6        17568 non-null  float64
 16  av_rech_amt_data_7        17865 non-null  float64
 17  av_rech_amt_data_8        18417 non-null  float64
 18  arpu_3g_6                 17568 non-null  float64
 19  arpu_3g_7                 17865 non-null  float64
 20  arpu_3g_8                 18417 non-null  float64
 21  arpu_2g_6                 17568 non-null  float64
 22  arpu_2g_7                 17865 non-null  float64
 23  arpu_2g_8                 18417 non-null  float64
 24  night_pck_user_6          17568 non-null  float64
 25  night_pck_user_7          17865 non-null  float64
 26  night_pck_user_8          18417 non-null  float64
 27  fb_user_6                 17568 non-null  float64
 28  fb_user_7                 17865 non-null  float64
 29  fb_user_8                 18417 non-null  float64
dtypes: float64(30)
memory usage: 16.6 MB

In [78]:
# check null percentage 

na_cols = dfx.columns[dfx.isna().sum()/dfx.shape[0]*100>0.7]
dfx[na_cols].describe().T

,count,mean,std,min,25%,50%,75%,max
loc_og_t2o_mou,69297.0,0.000000,0.000000,0.00,0.0000,0.000,0.0000,0.00
std_og_t2o_mou,69297.0,0.000000,0.000000,0.00,0.0000,0.000,0.0000,0.00
loc_ic_t2o_mou,69297.0,0.000000,0.000000,0.00,0.0000,0.000,0.0000,0.00
onnet_mou_6,67231.0,133.153275,299.963093,0.00,7.4100,34.110,119.3900,7376.71
onnet_mou_7,67312.0,133.894438,311.277193,0.00,6.6750,32.280,115.8375,8157.78
onnet_mou_8,66296.0,132.978257,311.896596,0.00,6.4100,32.100,115.0600,10752.56
offnet_mou_6,67231.0,198.874771,316.818355,0.00,34.8600,96.480,232.9900,8362.36
offnet_mou_7,67312.0,197.153383,322.482226,0.00,32.2400,91.885,227.6300,7043.98
offnet_mou_8,66296.0,196.543577,324.089234,0.00,31.5750,91.800,229.3450,14007.34
roam_ic_mou_6,67231.0,9.765435,57.374429,0.00,0.0000,0.000,0.0000,2850.98
roam_ic_mou_7,67312.0,7.014568,55.960985,0.00,0.0000,0.000,0.0000,4155.83
roam_ic_mou_8,66296.0,7.004892,53.408135,0.00,0.0000,0.000,0.0000,4169.81
roam_og_mou_6,67231.0,14.186457,73.469261,0.00,0.0000,0.000,0.0000,3775.11
roam_og_mou_7,67312.0,9.842191,58.511894,0.00,0.0000,0.000,0.0000,2812.04
roam_og_mou_8,66296.0,9.771783,64.618388,0.00,0.0000,0.000,0.0000,5337.04
loc_og_t2t_mou_6,67231.0,46.904854,150.971758,0.00,1.6600,11.910,40.7400,6431.33
loc_og_t2t_mou_7,67312.0,46.166503,154.739002,0.00,1.6500,11.580,39.7600,7400.66
loc_og_t2t_mou_8,66296.0,45.686109,153.716880,0.00,1.6100,11.740,39.8950,10752.56
loc_og_t2m_mou_6,67231.0,93.238231,162.046699,0.00,9.9200,41.030,110.4300,4696.83
loc_og_t2m_mou_7,67312.0,90.799240,153.852597,0.00,10.0900,40.170,107.5400,4557.14
loc_og_t2m_mou_8,66296.0,91.121447,152.997805,0.00,9.8300,40.350,109.2450,4961.33
loc_og_t2f_mou_6,67231.0,3.743179,13.319542,0.00,0.0000,0.000,2.0600,617.58
loc_og_t2f_mou_7,67312.0,3.777031,13.568110,0.00,0.0000,0.000,2.0800,815.33
loc_og_t2f_mou_8,66296.0,3.661652,13.009193,0.00,0.0000,0.000,2.0300,588.29
loc_og_t2c_mou_6,67231.0,1.126025,5.741811,0.00,0.0000,0.000,0.0000,342.86
loc_og_t2c_mou_7,67312.0,1.361052,7.914113,0.00,0.0000,0.000,0.0000,916.24
loc_og_t2c_mou_8,66296.0,1.420840,6.542202,0.00,0.0000,0.000,0.0000,351.83
loc_og_mou_6,67231.0,143.893585,252.034597,0.00,17.2350,65.190,167.8800,10643.38
loc_og_mou_7,67312.0,140.750120,246.313148,0.00,17.5900,63.430,163.9325,7674.78
loc_og_mou_8,66296.0,140.476486,245.342359,0.00,17.2375,63.520,165.6150,11039.91
std_og_t2t_mou_6,67231.0,80.619382,255.098355,0.00,0.0000,0.000,31.0200,7366.58
std_og_t2t_mou_7,67312.0,83.775851,266.693254,0.00,0.0000,0.000,31.3000,8133.66
std_og_t2t_mou_8,66296.0,83.471486,267.021929,0.00,0.0000,0.000,30.7600,8014.43
std_og_t2m_mou_6,67231.0,88.152110,255.771554,0.00,0.0000,3.980,53.7450,8314.76
std_og_t2m_mou_7,67312.0,91.538615,267.532089,0.00,0.0000,3.710,54.6400,6622.54
std_og_t2m_mou_8,66296.0,90.586999,270.032002,0.00,0.0000,3.300,52.6600,13950.04
std_og_t2f_mou_6,67231.0,1.126377,8.136645,0.00,0.0000,0.000,0.0000,628.56
std_og_t2f_mou_7,67312.0,1.084062,8.325206,0.00,0.0000,0.000,0.0000,465.79
std_og_t2f_mou_8,66296.0,1.057739,7.696853,0.00,0.0000,0.000,0.0000,354.16
std_og_t2c_mou_6,67231.0,0.000000,0.000000,0.00,0.0000,0.000,0.0000,0.00
std_og_t2c_mou_7,67312.0,0.000000,0.000000,0.00,0.0000,0.000,0.0000,0.00
std_og_t2c_mou_8,66296.0,0.000000,0.000000,0.00,0.0000,0.000,0.0000,0.00
std_og_mou_6,67231.0,169.900601,392.046600,0.00,0.0000,11.730,146.3350,8432.99
std_og_mou_7,67312.0,176.401217,409.299501,0.00,0.0000,11.260,151.6450,8155.53
std_og_mou_8,66296.0,175.118852,410.697098,0.00,0.0000,10.505,149.0150,13980.06
isd_og_mou_6,67231.0,0.845763,29.747486,0.00,0.0000,0.000,0.0000,5900.66
isd_og_mou_7,67312.0,0.811100,29.220073,0.00,0.0000,0.000,0.0000,5490.28
isd_og_mou_8,66296.0,0.841648,29.563367,0.00,0.0000,0.000,0.0000,5681.54
spl_og_mou_6,67231.0,3.958619,15.854529,0.00,0.0000,0.000,2.4000,1023.21
spl_og_mou_7,67312.0,4.976783,22.229842,0.00,0.0000,0.000,3.6600,2372.51
spl_og_mou_8,66296.0,5.045027,17.708507,0.00,0.0000,0.000,4.0025,1075.08
og_others_6,67231.0,0.462581,4.768437,0.00,0.0000,0.000,0.0000,800.89
og_others_7,67312.0,0.024425,1.716430,0.00,0.0000,0.000,0.0000,270.24
og_others_8,66296.0,0.033059,2.232547,0.00,0.0000,0.000,0.0000,394.93
loc_ic_t2t_mou_6,67231.0,48.043255,140.499757,0.00,3.0300,15.740,46.9800,5315.59
loc_ic_t2t_mou_7,67312.0,47.882736,147.761124,0.00,3.2600,15.830,45.6900,9324.66
loc_ic_t2t_mou_8,66296.0,47.256388,141.249368,0.00,3.2800,16.040,46.2800,10696.23
loc_ic_t2m_mou_6,67231.0,107.152439,168.455999,0.00,17.3900,56.460,132.0200,4450.74
loc_ic_t2m_mou_7,67312.0,106.489856,165.452459,0.00,18.6100,56.930,131.0100,4455.83
loc_ic_t2m_mou_8,66296.0,108.154731,166.223461,0.00,18.9400,58.210,134.3800,6274.19
loc_ic_t2f_mou_6,67231.0,12.050672,39.416076,0.00,0.0000,0.880,8.1400,1872.34
loc_ic_t2f_mou_7,67312.0,12.563665,43.495179,0.00,0.0000,0.910,8.2300,1983.01
loc_ic_t2f_mou_8,66296.0,11.716763,38.606895,0.00,0.0000,0.930,8.0900,1676.58
loc_ic_mou_6,67231.0,167.255126,252.576231,0.00,30.6300,92.430,208.3250,7454.63
loc_ic_mou_7,67312.0,166.945103,254.688718,0.00,32.7100,92.510,205.5300,9669.91
loc_ic_mou_8,66296.0,167.136761,249.288410,0.00,32.8100,93.890,208.0600,10830.16
std_ic_t2t_mou_6,67231.0,9.476958,51.664472,0.00,0.0000,0.000,4.0600,3336.38
std_ic_t2t_mou_7,67312.0,9.873468,56.137824,0.00,0.0000,0.000,4.1800,4708.71
std_ic_t2t_mou_8,66296.0,9.910217,54.248186,0.00,0.0000,0.000,4.0525,3930.24
std_ic_t2m_mou_6,67231.0,20.734858,80.294236,0.00,0.0000,2.040,14.9600,5647.16
std_ic_t2m_mou_7,67312.0,21.685359,87.314510,0.00,0.0000,2.060,15.8300,6141.88
std_ic_t2m_mou_8,66296.0,21.089042,81.534344,0.00,0.0000,2.030,15.3100,5512.76
std_ic_t2f_mou_6,67231.0,2.146273,16.522232,0.00,0.0000,0.000,0.0000,1351.11
std_ic_t2f_mou_7,67312.0,2.199395,16.171533,0.00,0.0000,0.000,0.0000,1136.08
std_ic_t2f_mou_8,66296.0,2.075179,15.865403,0.00,0.0000,0.000,0.0000,1394.89
std_ic_t2o_mou_6,67231.0,0.000000,0.000000,0.00,0.0000,0.000,0.0000,0.00
std_ic_t2o_mou_7,67312.0,0.000000,0.000000,0.00,0.0000,0.000,0.0000,0.00
std_ic_t2o_mou_8,66296.0,0.000000,0.000000,0.00,0.0000,0.000,0.0000,0.00
std_ic_mou_6,67231.0,32.360632,104.381082,0.00,0.0000,5.910,26.7800,5712.11
std_ic_mou_7,67312.0,33.760809,114.142230,0.00,0.0000,5.980,28.1600,6745.76
std_ic_mou_8,66296.0,33.077030,108.469864,0.00,0.0300,5.830,27.6150,5658.74
spl_ic_mou_6,67231.0,0.061932,0.164823,0.00,0.0000,0.000,0.0000,19.76
spl_ic_mou_7,67312.0,0.033371,0.137322,0.00,0.0000,0.000,0.0000,13.46
spl_ic_mou_8,66296.0,0.040392,0.148417,0.00,0.0000,0.000,0.0000,16.86
isd_ic_mou_6,67231.0,7.394167,60.951165,0.00,0.0000,0.000,0.0000,6789.41
isd_ic_mou_7,67312.0,8.171162,63.604165,0.00,0.0000,0.000,0.0000,5289.54
isd_ic_mou_8,66296.0,8.348424,63.097570,0.00,0.0000,0.000,0.0000,4127.01
ic_others_6,67231.0,0.854063,12.149144,0.00,0.0000,0.000,0.0000,1362.94
ic_others_7,67312.0,1.019680,13.225373,0.00,0.0000,0.000,0.0000,1495.94
ic_others_8,66296.0,0.963214,11.697686,0.00,0.0000,0.000,0.0000,1209.86
date_of_last_rech_6,68898.0,5.871869,6.134773,0.00,1.0000,3.000,9.0000,29.00
date_of_last_rech_data_6,68898.0,16250.172429,0.377755,16250.00,16250.0000,16250.000,16250.0000,16251.00
date_of_last_rech_data_7,17865.0,11.224685,8.822452,0.00,3.0000,9.000,18.0000,30.00
date_of_last_rech_data_8,18417.0,11.494597,8.908209,0.00,3.0000,10.000,19.0000,30.00
total_rech_data_6,17568.0,2.467612,2.794610,1.00,1.0000,1.000,3.0000,61.00
total_rech_data_7,17865.0,2.679989,3.073472,1.00,1.0000,2.000,3.0000,54.00
total_rech_data_8,18417.0,2.652441,3.101265,1.00,1.0000,1.000,3.0000,60.00
max_rech_data_6,17568.0,126.500000,109.352573,1.00,25.0000,145.000,177.0000,1555.00
max_rech_data_7,17865.0,126.402071,109.459266,1.00,25.0000,145.000,177.0000,1555.00
max_rech_data_8,18417.0,125.374925,109.648799,1.00,25.0000,145.000,179.0000,1555.00
count_rech_2g_6,17568.0,1.865323,2.566377,0.00,1.0000,1.000,2.0000,42.00
count_rech_2g_7,17865.0,2.056311,2.799916,0.00,1.0000,1.000,2.0000,48.00
count_rech_2g_8,18417.0,2.016018,2.728246,0.00,1.0000,1.000,2.0000,44.00
count_rech_3g_6,17568.0,0.602288,1.279297,0.00,0.0000,0.000,1.0000,29.00
count_rech_3g_7,17865.0,0.623678,1.401230,0.00,0.0000,0.000,1.0000,34.00
count_rech_3g_8,18417.0,0.636423,1.457058,0.00,0.0000,0.000,1.0000,45.00
av_rech_amt_data_6,17568.0,192.831096,190.623115,1.00,82.0000,154.000,252.0000,5920.00
av_rech_amt_data_7,17865.0,201.455940,198.346141,1.00,92.0000,154.000,252.0000,4365.00
av_rech_amt_data_8,18417.0,196.815792,192.280532,1.00,84.0000,154.000,252.0000,4076.00
arpu_3g_6,17568.0,90.069931,193.600413,-20.38,0.0000,0.520,122.0700,5054.37
arpu_3g_7,17865.0,89.115767,195.826990,-26.04,0.0000,0.420,120.8600,4980.90
arpu_3g_8,18417.0,90.618564,189.907986,-24.49,0.0000,0.840,122.0700,3716.90
arpu_2g_6,17568.0,86.863900,171.321203,-35.83,0.0000,11.300,122.0700,5054.35
arpu_2g_7,17865.0,85.846074,178.067280,-13.09,0.0000,8.800,122.0700,4809.36
arpu_2g_8,18417.0,86.348404,170.297094,-55.83,0.0000,9.090,122.0700,3483.17
night_pck_user_6,17568.0,0.025273,0.156958,0.00,0.0000,0.000,0.0000,1.00
night_pck_user_7,17865.0,0.024069,0.153269,0.00,0.0000,0.000,0.0000,1.00
night_pck_user_8,18417.0,0.021013,0.143432,0.00,0.0000,0.000,0.0000,1.00
fb_user_6,17568.0,0.916325,0.276907,0.00,1.0000,1.000,1.0000,1.00
fb_user_7,17865.0,0.909544,0.286842,0.00,1.0000,1.000,1.0000,1.00
fb_user_8,18417.0,0.890319,0.312501,0.00,1.0000,1.000,1.0000,1.00

In [80]:
dfx.columns[dfx.nunique()==1]

Index(['circle_id', 'loc_og_t2o_mou', 'std_og_t2o_mou', 'loc_ic_t2o_mou',
       'last_date_of_month_6', 'last_date_of_month_7', 'last_date_of_month_8',
       'std_og_t2c_mou_6', 'std_og_t2c_mou_7', 'std_og_t2c_mou_8',
       'std_ic_t2o_mou_6', 'std_ic_t2o_mou_7', 'std_ic_t2o_mou_8'],
      dtype='object')

In [81]:
# Drop columns with a single unique value

dfx.drop(dfx.columns[dfx.nunique()==1], axis = 1, inplace = True)

In [83]:
dfx.shape

(69999, 157)

In [84]:
 # Use only independent variables for check

x = dfx.copy()

In [85]:
# Find columns having only a single unique value.

x.columns[x.nunique()==1]

Index([], dtype='object')

No columns to drop

In [87]:
x.shape

(69999, 157)

In [88]:
x.columns[x.nunique()==2]

Index(['date_of_last_rech_data_6', 'night_pck_user_6', 'night_pck_user_7',
       'night_pck_user_8', 'fb_user_6', 'fb_user_7', 'fb_user_8'],
      dtype='object')

In [90]:
two_unique = x.columns[x.nunique()==2]
for col in two_unique:
    print(col, x[col].unique())

date_of_last_rech_data_6 [16250. 16251.    nan]
night_pck_user_6 [nan  0.  1.]
night_pck_user_7 [nan  0.  1.]
night_pck_user_8 [nan  0.  1.]
fb_user_6 [nan  1.  0.]
fb_user_7 [nan  1.  0.]
fb_user_8 [nan  1.  0.]

In [ ]:
x.columns[x.nunique()<=20]

Index(['monthly_2g_6', 'monthly_2g_7', 'monthly_2g_8', 'monthly_3g_6',
       'monthly_3g_7', 'monthly_3g_8'],
      dtype='object')

In [ ]:
# Find categorical variables

cols = x.columns[x.nunique()<=20]
for col in cols:
  print(col,':',x[col].unique())

monthly_2g_6 : [0 1 2 3 4]
monthly_2g_7 : [0 1 2 4 3 5]
monthly_2g_8 : [0 1 2 4 3 5]
monthly_3g_6 : [0 1 2 4 3 5 6 8 7 9]
monthly_3g_7 : [ 0  1  2  3  5  4  8  6  7 16 14  9 10]
monthly_3g_8 : [ 0  1  2  3  4  8  5  6  9  7 16 10]

In [ ]:
#xt.columns[xt.nunique()<=20]

In [ ]:
#xt.sachet_3g_8.unique()

In [ ]:
# Store categorical variables.

cat_vars = cols

In [ ]:
#xt.shape

### Get object columns and change data types to int/ float

In [ ]:
#objt = xt.columns[xt.dtypes=='O']
#objt

In [ ]:
obj = x.columns[x.dtypes=='O']
obj

Index(['date_of_last_rech_6', 'date_of_last_rech_7', 'date_of_last_rech_8'], dtype='object')

In [ ]:
for element in obj:
  x[element] = pd.to_datetime(x[element])
  #xt[element] = pd.to_datetime(xt[element])

In [ ]:
for element in obj:
  x[element] = (x[element] - x[element].min()).dt.days
  #xt[element] = (xt[element] - xt[element].min()).dt.days

In [ ]:
# x[obj]

### Null value imputation

In [ ]:
x_copy = x.copy()
#xt_copy = xt.copy()

In [ ]:
noncat = x.drop(cat_vars, axis = 1).columns
noncat

Index(['arpu_6', 'arpu_7', 'arpu_8', 'onnet_mou_6', 'onnet_mou_7',
       'onnet_mou_8', 'offnet_mou_6', 'offnet_mou_7', 'offnet_mou_8',
       'roam_ic_mou_6',
       ...
       'sachet_2g_6', 'sachet_2g_7', 'sachet_2g_8', 'sachet_3g_6',
       'sachet_3g_7', 'sachet_3g_8', 'aon', 'aug_vbc_3g', 'jul_vbc_3g',
       'jun_vbc_3g'],
      dtype='object', length=121)

In [ ]:
n_cat = x[noncat]
#nt_cat = xt[noncat]
med_cols = n_cat[n_cat.columns[abs(n_cat.mean() - n_cat.median())/n_cat.median()>=0.5]].columns
#medt_cols = nt_cat[nt_cat.columns[abs(nt_cat.mean() - nt_cat.median())/nt_cat.median()>=0.5]].columns

In [ ]:
mean_cols = n_cat.drop(med_cols, axis = 1).columns
#meant_cols = nt_cat.drop(medt_cols, axis = 1).columns

In [ ]:
#meant_cols

In [ ]:
from sklearn.impute import SimpleImputer
imp_mean = SimpleImputer(missing_values = np.nan, strategy = 'mean',verbose=0)
imp_med = SimpleImputer(missing_values = np.nan, strategy = 'median',verbose=0)
imp_mean = imp_mean.fit(x[mean_cols])
imp_med = imp_med.fit(x[med_cols])
x[mean_cols] = imp_mean.transform(x[mean_cols])
x[med_cols] = imp_med.transform(x[med_cols])

#impt_mean = imp_mean.fit(xt[meant_cols])
#impt_med = imp_med.fit(xt[medt_cols])
#xt[meant_cols] = impt_mean.transform(xt[meant_cols])
#xt[medt_cols] = impt_med.transform(xt[medt_cols])

In [ ]:
x.isna().sum()/x.shape[0]

arpu_6                 0.0
arpu_7                 0.0
arpu_8                 0.0
onnet_mou_6            0.0
onnet_mou_7            0.0
onnet_mou_8            0.0
offnet_mou_6           0.0
offnet_mou_7           0.0
offnet_mou_8           0.0
roam_ic_mou_6          0.0
roam_ic_mou_7          0.0
roam_ic_mou_8          0.0
roam_og_mou_6          0.0
roam_og_mou_7          0.0
roam_og_mou_8          0.0
loc_og_t2t_mou_6       0.0
loc_og_t2t_mou_7       0.0
loc_og_t2t_mou_8       0.0
loc_og_t2m_mou_6       0.0
loc_og_t2m_mou_7       0.0
loc_og_t2m_mou_8       0.0
loc_og_t2f_mou_6       0.0
loc_og_t2f_mou_7       0.0
loc_og_t2f_mou_8       0.0
loc_og_t2c_mou_6       0.0
loc_og_t2c_mou_7       0.0
loc_og_t2c_mou_8       0.0
loc_og_mou_6           0.0
loc_og_mou_7           0.0
loc_og_mou_8           0.0
std_og_t2t_mou_6       0.0
std_og_t2t_mou_7       0.0
std_og_t2t_mou_8       0.0
std_og_t2m_mou_6       0.0
std_og_t2m_mou_7       0.0
std_og_t2m_mou_8       0.0
std_og_t2f_mou_6       0.0
std_og_t2f_mou_7       0.0
std_og_t2f_mou_8       0.0
std_og_mou_6           0.0
std_og_mou_7           0.0
std_og_mou_8           0.0
isd_og_mou_6           0.0
isd_og_mou_7           0.0
isd_og_mou_8           0.0
spl_og_mou_6           0.0
spl_og_mou_7           0.0
spl_og_mou_8           0.0
og_others_6            0.0
og_others_7            0.0
og_others_8            0.0
total_og_mou_6         0.0
total_og_mou_7         0.0
total_og_mou_8         0.0
loc_ic_t2t_mou_6       0.0
loc_ic_t2t_mou_7       0.0
loc_ic_t2t_mou_8       0.0
loc_ic_t2m_mou_6       0.0
loc_ic_t2m_mou_7       0.0
loc_ic_t2m_mou_8       0.0
loc_ic_t2f_mou_6       0.0
loc_ic_t2f_mou_7       0.0
loc_ic_t2f_mou_8       0.0
loc_ic_mou_6           0.0
loc_ic_mou_7           0.0
loc_ic_mou_8           0.0
std_ic_t2t_mou_6       0.0
std_ic_t2t_mou_7       0.0
std_ic_t2t_mou_8       0.0
std_ic_t2m_mou_6       0.0
std_ic_t2m_mou_7       0.0
std_ic_t2m_mou_8       0.0
std_ic_t2f_mou_6       0.0
std_ic_t2f_mou_7       0.0
std_ic_t2f_mou_8       0.0
std_ic_mou_6           0.0
std_ic_mou_7           0.0
std_ic_mou_8           0.0
total_ic_mou_6         0.0
total_ic_mou_7         0.0
total_ic_mou_8         0.0
spl_ic_mou_6           0.0
spl_ic_mou_7           0.0
spl_ic_mou_8           0.0
isd_ic_mou_6           0.0
isd_ic_mou_7           0.0
isd_ic_mou_8           0.0
ic_others_6            0.0
ic_others_7            0.0
ic_others_8            0.0
total_rech_num_6       0.0
total_rech_num_7       0.0
total_rech_num_8       0.0
total_rech_amt_6       0.0
total_rech_amt_7       0.0
total_rech_amt_8       0.0
max_rech_amt_6         0.0
max_rech_amt_7         0.0
max_rech_amt_8         0.0
date_of_last_rech_6    0.0
date_of_last_rech_7    0.0
date_of_last_rech_8    0.0
last_day_rch_amt_6     0.0
last_day_rch_amt_7     0.0
last_day_rch_amt_8     0.0
vol_2g_mb_6            0.0
vol_2g_mb_7            0.0
vol_2g_mb_8            0.0
vol_3g_mb_6            0.0
vol_3g_mb_7            0.0
vol_3g_mb_8            0.0
monthly_2g_6           0.0
monthly_2g_7           0.0
monthly_2g_8           0.0
sachet_2g_6            0.0
sachet_2g_7            0.0
sachet_2g_8            0.0
monthly_3g_6           0.0
monthly_3g_7           0.0
monthly_3g_8           0.0
sachet_3g_6            0.0
sachet_3g_7            0.0
sachet_3g_8            0.0
aon                    0.0
aug_vbc_3g             0.0
jul_vbc_3g             0.0
jun_vbc_3g             0.0
dtype: float64

In [ ]:
xt.isna().sum()/xt.shape[0]*100

arpu_6                 0.0
arpu_7                 0.0
arpu_8                 0.0
onnet_mou_6            0.0
onnet_mou_7            0.0
onnet_mou_8            0.0
offnet_mou_6           0.0
offnet_mou_7           0.0
offnet_mou_8           0.0
roam_ic_mou_6          0.0
roam_ic_mou_7          0.0
roam_ic_mou_8          0.0
roam_og_mou_6          0.0
roam_og_mou_7          0.0
roam_og_mou_8          0.0
loc_og_t2t_mou_6       0.0
loc_og_t2t_mou_7       0.0
loc_og_t2t_mou_8       0.0
loc_og_t2m_mou_6       0.0
loc_og_t2m_mou_7       0.0
loc_og_t2m_mou_8       0.0
loc_og_t2f_mou_6       0.0
loc_og_t2f_mou_7       0.0
loc_og_t2f_mou_8       0.0
loc_og_t2c_mou_6       0.0
loc_og_t2c_mou_7       0.0
loc_og_t2c_mou_8       0.0
loc_og_mou_6           0.0
loc_og_mou_7           0.0
loc_og_mou_8           0.0
std_og_t2t_mou_6       0.0
std_og_t2t_mou_7       0.0
std_og_t2t_mou_8       0.0
std_og_t2m_mou_6       0.0
std_og_t2m_mou_7       0.0
std_og_t2m_mou_8       0.0
std_og_t2f_mou_6       0.0
std_og_t2f_mou_7       0.0
std_og_t2f_mou_8       0.0
std_og_mou_6           0.0
std_og_mou_7           0.0
std_og_mou_8           0.0
isd_og_mou_6           0.0
isd_og_mou_7           0.0
isd_og_mou_8           0.0
spl_og_mou_6           0.0
spl_og_mou_7           0.0
spl_og_mou_8           0.0
og_others_6            0.0
og_others_7            0.0
og_others_8            0.0
total_og_mou_6         0.0
total_og_mou_7         0.0
total_og_mou_8         0.0
loc_ic_t2t_mou_6       0.0
loc_ic_t2t_mou_7       0.0
loc_ic_t2t_mou_8       0.0
loc_ic_t2m_mou_6       0.0
loc_ic_t2m_mou_7       0.0
loc_ic_t2m_mou_8       0.0
loc_ic_t2f_mou_6       0.0
loc_ic_t2f_mou_7       0.0
loc_ic_t2f_mou_8       0.0
loc_ic_mou_6           0.0
loc_ic_mou_7           0.0
loc_ic_mou_8           0.0
std_ic_t2t_mou_6       0.0
std_ic_t2t_mou_7       0.0
std_ic_t2t_mou_8       0.0
std_ic_t2m_mou_6       0.0
std_ic_t2m_mou_7       0.0
std_ic_t2m_mou_8       0.0
std_ic_t2f_mou_6       0.0
std_ic_t2f_mou_7       0.0
std_ic_t2f_mou_8       0.0
std_ic_mou_6           0.0
std_ic_mou_7           0.0
std_ic_mou_8           0.0
total_ic_mou_6         0.0
total_ic_mou_7         0.0
total_ic_mou_8         0.0
spl_ic_mou_6           0.0
spl_ic_mou_7           0.0
spl_ic_mou_8           0.0
isd_ic_mou_6           0.0
isd_ic_mou_7           0.0
isd_ic_mou_8           0.0
ic_others_6            0.0
ic_others_7            0.0
ic_others_8            0.0
total_rech_num_6       0.0
total_rech_num_7       0.0
total_rech_num_8       0.0
total_rech_amt_6       0.0
total_rech_amt_7       0.0
total_rech_amt_8       0.0
max_rech_amt_6         0.0
max_rech_amt_7         0.0
max_rech_amt_8         0.0
date_of_last_rech_6    0.0
date_of_last_rech_7    0.0
date_of_last_rech_8    0.0
last_day_rch_amt_6     0.0
last_day_rch_amt_7     0.0
last_day_rch_amt_8     0.0
vol_2g_mb_6            0.0
vol_2g_mb_7            0.0
vol_2g_mb_8            0.0
vol_3g_mb_6            0.0
vol_3g_mb_7            0.0
vol_3g_mb_8            0.0
sachet_2g_6            0.0
sachet_2g_7            0.0
sachet_2g_8            0.0
sachet_3g_6            0.0
sachet_3g_7            0.0
sachet_3g_8            0.0
aon                    0.0
aug_vbc_3g             0.0
jul_vbc_3g             0.0
jun_vbc_3g             0.0
monthly_2g_6_1         0.0
monthly_2g_6_2         0.0
monthly_2g_6_3         0.0
monthly_2g_6_4         0.0
monthly_2g_7_1         0.0
monthly_2g_7_2         0.0
monthly_2g_7_3         0.0
monthly_2g_7_4         0.0
monthly_2g_7_5         0.0
monthly_2g_8_1         0.0
monthly_2g_8_2         0.0
monthly_2g_8_3         0.0
monthly_2g_8_4         0.0
monthly_2g_8_5         0.0
monthly_3g_6_1         0.0
monthly_3g_6_2         0.0
monthly_3g_6_3         0.0
monthly_3g_6_4         0.0
monthly_3g_6_5         0.0
monthly_3g_6_6         0.0
monthly_3g_6_7         0.0
monthly_3g_6_8         0.0
monthly_3g_6_9         0.0
monthly_3g_6_11        0.0
monthly_3g_6_14        0.0
monthly_3g_7_1         0.0
monthly_3g_7_2         0.0
monthly_3g_7_3         0.0
monthly_3g_7_4         0.0
monthly_3g_7_5         0.0
monthly_3g_7_6         0.0
monthly_3g_7_7         0.0
monthly_3g_7_8         0.0
monthly_3g_7_9         0.0
monthly_3g_7_10        0.0
monthly_3g_7_11        0.0
monthly_3g_7_12        0.0
monthly_3g_7_14        0.0
monthly_3g_7_16        0.0
monthly_3g_8_1         0.0
monthly_3g_8_2         0.0
monthly_3g_8_3         0.0
monthly_3g_8_4         0.0
monthly_3g_8_5         0.0
monthly_3g_8_6         0.0
monthly_3g_8_7         0.0
monthly_3g_8_8         0.0
monthly_3g_8_9         0.0
monthly_3g_8_10        0.0
monthly_3g_8_16        0.0
dtype: float64

In [ ]:
print("printing the count of infinity values")
  
count = np.isinf(x).values.sum()
print("Train dataset contains " + str(count) + " infinite values")

#print("\nprinting the count of infinity values")
  
#count = np.isinf(xt).values.sum()
#print("Test dataset contains " + str(count) + " infinite values")

printing the count of infinity values
Train dataset contains 0 infinite values

In [ ]:
# Check for null values in categorical variables

x[cat_vars].isna().sum()/x[cat_vars].shape[0]*100

monthly_2g_6    0.0
monthly_2g_7    0.0
monthly_2g_8    0.0
monthly_3g_6    0.0
monthly_3g_7    0.0
monthly_3g_8    0.0
dtype: float64

In [ ]:
# xt[cat_vars].isna().sum()/xt[cat_vars].shape[0]*100

In [ ]:
# xt.columns[xt.dtypes=='O']

## Data Preparation

In [ ]:
x_copy = x.copy()
# xt_copy = xt.copy()

In [ ]:
x.shape

(69999, 127)

In [ ]:
test.shape

(30000, 171)

In [ ]:
xt = test[x.columns]

In [ ]:
obj

Index(['date_of_last_rech_6', 'date_of_last_rech_7', 'date_of_last_rech_8'], dtype='object')

In [ ]:
for ele in obj:
    xt[ele] = pd.to_datetime(xt[ele])
    xt[ele] = (xt[ele] - xt[ele].min()).dt.days

In [ ]:
imp_mean = SimpleImputer(missing_values = np.nan, strategy = 'mean',verbose=0)
imp_med = SimpleImputer(missing_values = np.nan, strategy = 'median',verbose=0)
impt_mean = imp_mean.fit(xt[mean_cols])
impt_med = imp_med.fit(xt[med_cols])
xt[mean_cols] = impt_mean.transform(xt[mean_cols])
xt[med_cols] = impt_med.transform(xt[med_cols])

In [ ]:
x.shape

(69999, 127)

In [ ]:
xt.shape

(30000, 127)

In [ ]:
cat_vars

Index(['monthly_2g_6', 'monthly_2g_7', 'monthly_2g_8', 'monthly_3g_6',
       'monthly_3g_7', 'monthly_3g_8'],
      dtype='object')

In [ ]:
for ele in cat_vars:
    print(ele)
    print('x',x[ele].nunique())
    print('xt',xt[ele].nunique())
    print()

monthly_2g_6
x 5
xt 5

monthly_2g_7
x 6
xt 6

monthly_2g_8
x 6
xt 6

monthly_3g_6
x 10
xt 11

monthly_3g_7
x 13
xt 12

monthly_3g_8
x 12
xt 10

In [ ]:
x_all = pd.concat([x,xt])

In [ ]:
x_all.shape

(99999, 127)

In [ ]:
# Get dummies for categorical variables.

x_all = pd.get_dummies(data=x_all, columns=cat_vars, drop_first = True)

In [ ]:
xt = x_all.iloc[-30000:]

In [ ]:
xt.shape

(30000, 171)

In [ ]:
x = x_all.iloc[:-30000]

In [ ]:
x.shape

(69999, 171)

In [ ]:
y = df['churn_probability']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.25, random_state = 100, stratify=y)

In [ ]:
X_train.shape

(52499, 171)

In [ ]:
y_train.shape

(52499,)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_unseen = scaler.transform(xt)

In [ ]:
df_train = pd.DataFrame(X_train, columns = x.columns)

In [ ]:
df_train.describe().T

,count,mean,std,min,25%,50%,75%,max
arpu_6,52499.0,-2.125599e-16,1.00001,-7.673722,-0.571863,-0.257771,0.263829,82.862033
arpu_7,52499.0,3.390157e-17,1.00001,-4.507347,-0.551752,-0.248822,0.251346,100.261270
arpu_8,52499.0,-1.237023e-17,1.00001,-3.547012,-0.564307,-0.250763,0.267286,96.386162
onnet_mou_6,52499.0,-2.355727e-16,1.00001,-0.436732,-0.409598,-0.321899,-0.053082,24.397195
onnet_mou_7,52499.0,1.088600e-16,1.00001,-0.423414,-0.399921,-0.318668,-0.066635,26.047920
onnet_mou_8,52499.0,-7.604600e-17,1.00001,-0.416496,-0.392808,-0.312192,-0.069142,34.522128
offnet_mou_6,52499.0,1.005966e-16,1.00001,-0.627679,-0.509054,-0.317853,0.096100,26.226389
offnet_mou_7,52499.0,-1.682644e-16,1.00001,-0.610059,-0.502737,-0.320788,0.080447,21.565629
offnet_mou_8,52499.0,-1.830888e-16,1.00001,-0.611006,-0.501262,-0.318439,0.082343,23.164718
roam_ic_mou_6,52499.0,-1.977007e-16,1.00001,-0.166787,-0.166787,-0.166787,-0.166787,49.726234
roam_ic_mou_7,52499.0,3.514052e-16,1.00001,-0.122210,-0.122210,-0.122210,-0.122210,73.889133
roam_ic_mou_8,52499.0,9.435040e-17,1.00001,-0.132113,-0.132113,-0.132113,-0.132113,58.125881
roam_og_mou_6,52499.0,1.866743e-15,1.00001,-0.193575,-0.193575,-0.193575,-0.193575,32.662861
roam_og_mou_7,52499.0,6.764866e-16,1.00001,-0.163564,-0.163564,-0.163564,-0.163564,47.752681
roam_og_mou_8,52499.0,-2.343731e-16,1.00001,-0.144122,-0.144122,-0.144122,-0.144122,82.365772
loc_og_t2t_mou_6,52499.0,-1.113406e-16,1.00001,-0.313629,-0.300522,-0.231033,-0.044621,44.287607
loc_og_t2t_mou_7,52499.0,1.294767e-16,1.00001,-0.296598,-0.284161,-0.219988,-0.045962,48.664096
loc_og_t2t_mou_8,52499.0,9.547465e-17,1.00001,-0.286014,-0.273447,-0.209965,-0.044132,69.367068
loc_og_t2m_mou_6,52499.0,-4.701725e-17,1.00001,-0.570623,-0.503402,-0.314771,0.089335,25.694514
loc_og_t2m_mou_7,52499.0,-1.190732e-16,1.00001,-0.585573,-0.514094,-0.321786,0.093629,29.340149
loc_og_t2m_mou_8,52499.0,-3.996985e-17,1.00001,-0.587486,-0.514386,-0.321517,0.092430,32.115256
loc_og_t2f_mou_6,52499.0,1.387441e-15,1.00001,-0.274210,-0.274210,-0.274210,-0.131866,46.988739
loc_og_t2f_mou_7,52499.0,-7.897960e-16,1.00001,-0.271798,-0.271798,-0.271798,-0.130127,61.168922
loc_og_t2f_mou_8,52499.0,3.987468e-16,1.00001,-0.282677,-0.282677,-0.282677,-0.136127,44.284187
loc_og_t2c_mou_6,52499.0,-2.968507e-16,1.00001,-0.197281,-0.197281,-0.197281,-0.197281,63.229461
loc_og_t2c_mou_7,52499.0,2.543480e-15,1.00001,-0.194354,-0.194354,-0.194354,-0.194354,69.447814
loc_og_t2c_mou_8,52499.0,-1.270046e-15,1.00001,-0.216064,-0.216064,-0.216064,-0.216064,50.180854
loc_og_mou_6,52499.0,5.650826e-17,1.00001,-0.568893,-0.493617,-0.305489,0.084042,42.436395
loc_og_mou_7,52499.0,-9.320341e-17,1.00001,-0.567378,-0.489543,-0.306709,0.083040,30.972453
loc_og_mou_8,52499.0,-1.725393e-16,1.00001,-0.560275,-0.481696,-0.301119,0.083576,44.481617
std_og_t2t_mou_6,52499.0,1.486599e-15,1.00001,-0.305983,-0.305983,-0.305983,-0.198647,28.530434
std_og_t2t_mou_7,52499.0,-8.751727e-16,1.00001,-0.305844,-0.305844,-0.305844,-0.202261,30.398034
std_og_t2t_mou_8,52499.0,1.612806e-15,1.00001,-0.303237,-0.303237,-0.303237,-0.207525,30.343047
std_og_t2m_mou_6,52499.0,-9.032629e-17,1.00001,-0.339084,-0.339084,-0.323261,-0.141342,32.716412
std_og_t2m_mou_7,52499.0,-1.229244e-15,1.00001,-0.336674,-0.336674,-0.322579,-0.144114,24.823362
std_og_t2m_mou_8,52499.0,-1.145049e-15,1.00001,-0.332052,-0.332052,-0.319322,-0.153295,26.973900
std_og_t2f_mou_6,52499.0,3.343739e-15,1.00001,-0.135794,-0.135794,-0.135794,-0.135794,78.996625
std_og_t2f_mou_7,52499.0,-2.458092e-15,1.00001,-0.128513,-0.128513,-0.128513,-0.128513,57.449315
std_og_t2f_mou_8,52499.0,8.703458e-16,1.00001,-0.134100,-0.134100,-0.134100,-0.134100,47.249918
std_og_mou_6,52499.0,-1.188126e-15,1.00001,-0.422842,-0.422842,-0.392752,-0.074505,21.209174
std_og_mou_7,52499.0,-4.749635e-16,1.00001,-0.421873,-0.421873,-0.394088,-0.080438,19.702316
std_og_mou_8,52499.0,-1.931471e-16,1.00001,-0.418238,-0.418238,-0.391892,-0.087743,19.981436
isd_og_mou_6,52499.0,-1.158235e-15,1.00001,-0.037444,-0.037444,-0.037444,-0.037444,169.425335
isd_og_mou_7,52499.0,-1.676746e-15,1.00001,-0.033134,-0.033134,-0.033134,-0.033134,181.446509
isd_og_mou_8,52499.0,7.506543e-16,1.00001,-0.035292,-0.035292,-0.035292,-0.035292,179.208987
spl_og_mou_6,52499.0,5.388459e-16,1.00001,-0.262623,-0.262623,-0.262623,-0.112424,59.454550
spl_og_mou_7,52499.0,-4.170759e-16,1.00001,-0.221914,-0.221914,-0.221914,-0.066419,111.569855
spl_og_mou_8,52499.0,1.507912e-16,1.00001,-0.277994,-0.277994,-0.277994,-0.071423,55.578655
og_others_6,52499.0,1.723055e-15,1.00001,-0.118892,-0.118892,-0.118892,-0.118892,168.856858
og_others_7,52499.0,3.966389e-16,1.00001,-0.014439,-0.014439,-0.014439,-0.014439,202.831321
og_others_8,52499.0,1.292606e-15,1.00001,-0.014143,-0.014143,-0.014143,-0.014143,159.969377
total_og_mou_6,52499.0,1.705018e-16,1.00001,-0.656481,-0.560274,-0.344487,0.144465,22.128352
total_og_mou_7,52499.0,-1.731431e-16,1.00001,-0.646124,-0.556926,-0.351989,0.144967,16.533457
total_og_mou_8,52499.0,-8.683590e-17,1.00001,-0.638734,-0.557869,-0.349249,0.140099,22.443843
loc_ic_t2t_mou_6,52499.0,9.522511e-17,1.00001,-0.334721,-0.311437,-0.223494,-0.018778,37.227905
loc_ic_t2t_mou_7,52499.0,2.782378e-17,1.00001,-0.313349,-0.289607,-0.208660,-0.022296,61.353631
loc_ic_t2t_mou_8,52499.0,-6.106713e-17,1.00001,-0.321310,-0.295491,-0.210279,-0.018259,73.719337
loc_ic_t2m_mou_6,52499.0,-1.796735e-16,1.00001,-0.642217,-0.528286,-0.296008,0.133963,23.115916
loc_ic_t2m_mou_7,52499.0,-1.111280e-16,1.00001,-0.645125,-0.523816,-0.294205,0.137311,26.820915
loc_ic_t2m_mou_8,52499.0,-6.876007e-17,1.00001,-0.651798,-0.524856,-0.292396,0.138999,38.086557
loc_ic_t2f_mou_6,52499.0,8.043412e-16,1.00001,-0.302337,-0.302337,-0.279498,-0.106648,35.587662
loc_ic_t2f_mou_7,52499.0,-3.386752e-16,1.00001,-0.284275,-0.284275,-0.263098,-0.106714,45.863323
loc_ic_t2f_mou_8,52499.0,2.845503e-16,1.00001,-0.297255,-0.297255,-0.272535,-0.103744,42.208153
loc_ic_mou_6,52499.0,6.512375e-17,1.00001,-0.663616,-0.531622,-0.290751,0.141294,22.945975
loc_ic_mou_7,52499.0,4.305633e-17,1.00001,-0.649445,-0.513402,-0.285285,0.135325,37.415646
loc_ic_mou_8,52499.0,-1.825231e-16,1.00001,-0.664146,-0.520812,-0.284308,0.140114,43.150054
std_ic_t2t_mou_6,52499.0,-4.911197e-16,1.00001,-0.190117,-0.190117,-0.190117,-0.113068,63.771240
std_ic_t2t_mou_7,52499.0,1.477502e-16,1.00001,-0.178801,-0.178801,-0.178801,-0.107171,79.867462
std_ic_t2t_mou_8,52499.0,7.131809e-16,1.00001,-0.183823,-0.183823,-0.183823,-0.114650,67.475200
std_ic_t2m_mou_6,52499.0,4.378766e-16,1.00001,-0.245704,-0.245704,-0.220813,-0.073906,68.658490
std_ic_t2m_mou_7,52499.0,2.361733e-16,1.00001,-0.237228,-0.237228,-0.214009,-0.068835,68.989631
std_ic_t2m_mou_8,52499.0,9.615735e-16,1.00001,-0.247629,-0.247629,-0.222630,-0.074113,67.641114
std_ic_t2f_mou_6,52499.0,-1.663119e-15,1.00001,-0.121844,-0.121844,-0.121844,-0.121844,77.243939
std_ic_t2f_mou_7,52499.0,-9.319094e-16,1.00001,-0.128584,-0.128584,-0.128584,-0.128584,67.866612
std_ic_t2f_mou_8,52499.0,1.355631e-15,1.00001,-0.127373,-0.127373,-0.127373,-0.127373,90.574708
std_ic_mou_6,52499.0,-8.360858e-16,1.00001,-0.304702,-0.303539,-0.247439,-0.059469,55.040789
std_ic_mou_7,52499.0,2.661551e-16,1.00001,-0.292195,-0.291215,-0.238936,-0.055468,56.374336
std_ic_mou_8,52499.0,-9.380294e-17,1.00001,-0.297732,-0.295846,-0.242753,-0.055937,53.066449
total_ic_mou_6,52499.0,-8.714465e-17,1.00001,-0.690954,-0.555634,-0.296789,0.173350,23.740044
total_ic_mou_7,52499.0,-5.705175e-17,1.00001,-0.679198,-0.540296,-0.290648,0.158967,31.791534
total_ic_mou_8,52499.0,8.640026e-17,1.00001,-0.684150,-0.552604,-0.291261,0.173541,36.475299
spl_ic_mou_6,52499.0,9.709128e-16,1.00001,-0.410981,-0.410981,-0.410981,-0.410981,20.294420
spl_ic_mou_7,52499.0,7.704037e-16,1.00001,-0.251253,-0.251253,-0.251253,-0.251253,54.957982
spl_ic_mou_8,52499.0,5.967294e-15,1.00001,-0.257351,-0.257351,-0.257351,-0.257351,113.638725
isd_ic_mou_6,52499.0,-5.761866e-16,1.00001,-0.118769,-0.118769,-0.118769,-0.118769,113.866435
isd_ic_mou_7,52499.0,-8.519178e-16,1.00001,-0.131509,-0.131509,-0.131509,-0.131509,75.733011
isd_ic_mou_8,52499.0,9.316588e-16,1.00001,-0.132736,-0.132736,-0.132736,-0.132736,56.922416
ic_others_6,52499.0,2.214544e-15,1.00001,-0.076381,-0.076381,-0.076381,-0.076381,131.068542
ic_others_7,52499.0,-8.123762e-17,1.00001,-0.072698,-0.072698,-0.072698,-0.072698,111.003508
ic_others_8,52499.0,1.564182e-15,1.00001,-0.077260,-0.077260,-0.077260,-0.077260,103.054819
total_rech_num_6,52499.0,1.868509e-16,1.00001,-1.086500,-0.654030,-0.221560,0.210909,15.779815
total_rech_num_7,52499.0,1.620470e-16,1.00001,-1.102284,-0.670739,-0.239193,0.336201,16.015691
total_rech_num_8,52499.0,-3.109070e-16,1.00001,-1.012544,-0.589180,-0.306938,0.257547,15.357524
total_rech_amt_6,52499.0,9.721509e-17,1.00001,-0.814965,-0.541738,-0.246157,0.272973,86.592605
total_rech_amt_7,52499.0,-8.425379e-17,1.00001,-0.776139,-0.535122,-0.245902,0.257823,96.437993
total_rech_amt_8,52499.0,-2.691443e-17,1.00001,-0.764322,-0.551649,-0.232639,0.265961,106.328364
max_rech_amt_6,52499.0,4.750407e-16,1.00001,-0.848133,-0.605347,0.042081,0.123009,31.604195
max_rech_amt_7,52499.0,-5.129328e-17,1.00001,-0.859271,-0.612281,0.046359,0.194553,26.301383
max_rech_amt_8,52499.0,-4.462124e-18,1.00001,-0.852875,-0.616133,-0.079519,0.283486,34.255943
date_of_last_rech_6,52499.0,-1.533533e-16,1.00001,-3.797765,-0.511035,0.474985,0.803658,0.967994
date_of_last_rech_7,52499.0,1.232244e-16,1.00001,-4.290481,-0.438090,0.262345,0.787671,0.962780
date_of_last_rech_8,52499.0,-5.472806e-16,1.00001,-4.067369,-0.237645,0.261885,0.761414,0.927923
last_day_rch_amt_6,52499.0,-3.437612e-16,1.00001,-0.636165,-0.636165,-0.337648,0.458397,39.265597
last_day_rch_amt_7,52499.0,-4.727356e-16,1.00001,-0.617494,-0.617494,-0.306734,0.521959,31.494371
last_day_rch_amt_8,52499.0,-7.412233e-16,1.00001,-0.603434,-0.603434,-0.315386,0.644773,42.114027
vol_2g_mb_6,52499.0,-7.864282e-16,1.00001,-0.240710,-0.240710,-0.240710,-0.240710,48.419992
vol_2g_mb_7,52499.0,1.417774e-15,1.00001,-0.243635,-0.243635,-0.243635,-0.243635,26.682897
vol_2g_mb_8,52499.0,-8.556694e-16,1.00001,-0.235163,-0.235163,-0.235163,-0.235163,52.279336
vol_3g_mb_6,52499.0,1.484263e-15,1.00001,-0.220471,-0.220471,-0.220471,-0.220471,83.447415
vol_3g_mb_7,52499.0,-2.518066e-16,1.00001,-0.228671,-0.228671,-0.228671,-0.228671,49.944448
vol_3g_mb_8,52499.0,-3.363760e-15,1.00001,-0.240697,-0.240697,-0.240697,-0.240697,53.390637
sachet_2g_6,52499.0,-6.954569e-16,1.00001,-0.261258,-0.261258,-0.261258,-0.261258,28.412849
sachet_2g_7,52499.0,-2.424801e-15,1.00001,-0.267849,-0.267849,-0.267849,-0.267849,21.276700
sachet_2g_8,52499.0,-1.995344e-15,1.00001,-0.275046,-0.275046,-0.275046,-0.275046,27.083352
sachet_3g_6,52499.0,8.179095e-16,1.00001,-0.131829,-0.131829,-0.131829,-0.131829,51.120878
sachet_3g_7,52499.0,4.745708e-15,1.00001,-0.130259,-0.130259,-0.130259,-0.130259,53.498202
sachet_3g_8,52499.0,6.554892e-16,1.00001,-0.129216,-0.129216,-0.129216,-0.129216,64.552560
aon,52499.0,1.025866e-17,1.00001,-1.092571,-0.792184,-0.370387,0.630728,3.258326
aug_vbc_3g,52499.0,3.592598e-15,1.00001,-0.258906,-0.258906,-0.258906,-0.258906,31.281130
jul_vbc_3g,52499.0,-2.185372e-15,1.00001,-0.246438,-0.246438,-0.246438,-0.246438,34.315164
jun_vbc_3g,52499.0,-8.090180e-16,1.00001,-0.233262,-0.233262,-0.233262,-0.233262,43.616265
monthly_2g_6_1,52499.0,-1.270069e-15,1.00001,-0.266609,-0.266609,-0.266609,-0.266609,3.750813
monthly_2g_6_2,52499.0,-1.617553e-15,1.00001,-0.075428,-0.075428,-0.075428,-0.075428,13.257613
monthly_2g_6_3,52499.0,-1.691240e-15,1.00001,-0.017460,-0.017460,-0.017460,-0.017460,57.272921
monthly_2g_6_4,52499.0,1.960529e-15,1.00001,-0.009760,-0.009760,-0.009760,-0.009760,102.463652
monthly_2g_7_1,52499.0,-2.183605e-15,1.00001,-0.271777,-0.271777,-0.271777,-0.271777,3.679488
monthly_2g_7_2,52499.0,1.743838e-15,1.00001,-0.082042,-0.082042,-0.082042,-0.082042,12.188921
monthly_2g_7_3,52499.0,-1.233030e-15,1.00001,-0.018520,-0.018520,-0.018520,-0.018520,53.996399
monthly_2g_7_4,52499.0,1.854639e-15,1.00001,-0.006172,-0.006172,-0.006172,-0.006172,162.013888
monthly_2g_7_5,52499.0,-7.645473e-16,1.00001,-0.004364,-0.004364,-0.004364,-0.004364,229.124420
monthly_2g_8_1,52499.0,4.313584e-16,1.00001,-0.268530,-0.268530,-0.268530,-0.268530,3.723980
monthly_2g_8_2,52499.0,-6.892073e-16,1.00001,-0.077321,-0.077321,-0.077321,-0.077321,12.933137
monthly_2g_8_3,52499.0,8.861239e-16,1.00001,-0.019027,-0.019027,-0.019027,-0.019027,52.555735
monthly_2g_8_4,52499.0,2.478169e-15,1.00001,-0.006172,-0.006172,-0.006172,-0.006172,162.013888
monthly_2g_8_5,52499.0,1.953977e-15,1.00001,-0.004364,-0.004364,-0.004364,-0.004364,229.124420
monthly_3g_6_1,52499.0,1.618864e-15,1.00001,-0.214877,-0.214877,-0.214877,-0.214877,4.653835
monthly_3g_6_2,52499.0,-2.480918e-15,1.00001,-0.093709,-0.093709,-0.093709,-0.093709,10.671338
monthly_3g_6_3,52499.0,6.555201e-16,1.00001,-0.048262,-0.048262,-0.048262,-0.048262,20.720031
monthly_3g_6_4,52499.0,-1.771362e-15,1.00001,-0.031789,-0.031789,-0.031789,-0.031789,31.457069
monthly_3g_6_5,52499.0,1.169550e-15,1.00001,-0.015738,-0.015738,-0.015738,-0.015738,63.540417
monthly_3g_6_6,52499.0,2.613901e-15,1.00001,-0.012345,-0.012345,-0.012345,-0.012345,81.002315
monthly_3g_6_7,52499.0,-1.180249e-15,1.00001,-0.011548,-0.011548,-0.011548,-0.011548,86.595942
monthly_3g_6_8,52499.0,-4.773435e-16,1.00001,-0.004364,-0.004364,-0.004364,-0.004364,229.124420
monthly_3g_6_9,52499.0,-5.114502e-16,1.00001,-0.004364,-0.004364,-0.004364,-0.004364,229.124420
monthly_3g_6_11,52499.0,0.000000e+00,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
monthly_3g_6_14,52499.0,0.000000e+00,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
monthly_3g_7_1,52499.0,-1.837034e-15,1.00001,-0.208243,-0.208243,-0.208243,-0.208243,4.802087
monthly_3g_7_2,52499.0,-1.738176e-15,1.00001,-0.100214,-0.100214,-0.100214,-0.100214,9.978617
monthly_3g_7_3,52499.0,-8.798413e-16,1.00001,-0.049244,-0.049244,-0.049244,-0.049244,20.307091
monthly_3g_7_4,52499.0,-8.782099e-16,1.00001,-0.028296,-0.028296,-0.028296,-0.028296,35.340857
monthly_3g_7_5,52499.0,-4.871799e-16,1.00001,-0.020004,-0.020004,-0.020004,-0.020004,49.989523
monthly_3g_7_6,52499.0,9.557061e-16,1.00001,-0.015738,-0.015738,-0.015738,-0.015738,63.540417
monthly_3g_7_7,52499.0,-1.199936e-16,1.00001,-0.008729,-0.008729,-0.008729,-0.008729,114.558937
monthly_3g_7_8,52499.0,2.245919e-15,1.00001,-0.006172,-0.006172,-0.006172,-0.006172,162.013888
monthly_3g_7_9,52499.0,2.995074e-15,1.00001,-0.007560,-0.007560,-0.007560,-0.007560,132.282526
monthly_3g_7_10,52499.0,0.000000e+00,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
monthly_3g_7_11,52499.0,0.000000e+00,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
monthly_3g_7_12,52499.0,0.000000e+00,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
monthly_3g_7_14,52499.0,4.213136e-15,1.00001,-0.004364,-0.004364,-0.004364,-0.004364,229.124420
monthly_3g_7_16,52499.0,2.253358e-15,1.00001,-0.004364,-0.004364,-0.004364,-0.004364,229.124420
monthly_3g_8_1,52499.0,3.389103e-15,1.00001,-0.218011,-0.218011,-0.218011,-0.218011,4.586925
monthly_3g_8_2,52499.0,-5.831462e-16,1.00001,-0.101275,-0.101275,-0.101275,-0.101275,9.874066
monthly_3g_8_3,52499.0,8.080391e-16,1.00001,-0.053529,-0.053529,-0.053529,-0.053529,18.681363
monthly_3g_8_4,52499.0,5.737866e-16,1.00001,-0.031789,-0.031789,-0.031789,-0.031789,31.457069
monthly_3g_8_5,52499.0,1.405033e-15,1.00001,-0.019027,-0.019027,-0.019027,-0.019027,52.555735
monthly_3g_8_6,52499.0,2.004308e-15,1.00001,-0.010691,-0.010691,-0.010691,-0.010691,93.535198
monthly_3g_8_7,52499.0,2.086754e-15,1.00001,-0.006172,-0.006172,-0.006172,-0.006172,162.013888
monthly_3g_8_8,52499.0,2.360149e-15,1.00001,-0.006172,-0.006172,-0.006172,-0.006172,162.013888
monthly_3g_8_9,52499.0,1.828518e-15,1.00001,-0.006172,-0.006172,-0.006172,-0.006172,162.013888
monthly_3g_8_10,52499.0,3.400801e-15,1.00001,-0.004364,-0.004364,-0.004364,-0.004364,229.124420
monthly_3g_8_16,52499.0,0.000000e+00,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000

In [ ]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 0.85, svd_solver = 'full', random_state = 100)
principalComponents = pca.fit_transform(X_train)
principalDf = pd.DataFrame(data = principalComponents)
                           # columns = ['pca1','pca2'])

In [ ]:
# pca = PCA(n_components = 2, random_state = 100)
# principalComponents = pca.fit_transform(X_train)
# principalDf = pd.DataFrame(data = principalComponents)

In [ ]:
# principalDf.shape

In [ ]:
# principalDf.columns

In [ ]:
test_components = pca.transform(X_test)
X_test_pca = pd.DataFrame(data = test_components)

In [ ]:
from sklearn.linear_model import LogisticRegression
X_train_pca = principalDf.copy()
logistic=LogisticRegression()
logistic.fit(X=X_train_pca,y=y_train)
logistic.predict(X_test_pca)
score_2=logistic.score(X_test_pca,y_test)
print(score_2)

0.9034285714285715

In [ ]:
"{:2.2}".format(metrics.roc_auc_score(y_test, pred_proba[:,1]))

'0.7'

In [ ]:
pred_proba = logistic.predict_proba(X_test_pca)

In [ ]:
y_pred = np.round(pred_proba[:,1],0)

In [ ]:
metrics.accuracy_score(y_test, y_pred)

0.8981142857142858

In [ ]:
# Transform on unseen data

# pca = PCA(n_components = 2, random_state = 100)
pcomp_unseen = pca.transform(xt)
princDf_unseen = pd.DataFrame(data = pcomp_unseen)

In [ ]:
unseen_predict = logistic.predict(princDf_unseen)
# score_2=logistic.score(princDf_unseen,y_test)
# print(score_2)

In [ ]:
unseen_pred = pd.DataFrame(unseen_predict)

In [ ]:
unseen_pred.groupby(0)[0].count()

0
0    29466
1      534
Name: 0, dtype: int64

In [ ]:
unseen_pred = unseen_pred.reset_index()

In [ ]:
unseen_pred.columns

Index(['index', 0], dtype='object')

In [ ]:
unseen_pred.rename(columns={'index':'id',0:'churn_probability'}, inplace=True)

In [ ]:
unseen_pred.columns

Index(['id', 'churn_probability'], dtype='object')

In [ ]:
unseen_pred['id'] = unseen_pred['id'] + 69999

In [ ]:
unseen_pred.head()

      id  churn_probability
0  69999                  0
1  70000                  0
2  70001                  0
3  70002                  0
4  70003                  0

In [ ]:
unseen_pred.to_csv('Ram_Prayag.csv',index = False)

## Test set data preparation

## Support Vector Machine

In [ ]:
import numpy as np
import cvxopt
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
from sklearn.svm import LinearSVC
from sklearn.metrics import confusion_matrix

In [ ]:
x['churn_probability'] = df['churn_probability']

In [ ]:
y_train.shape

(48999,)

In [ ]:
X_train.shape

(48999, 168)

In [ ]:
from sklearn import svm

In [ ]:
svm = svm.SVC()
svm.fit(X_train, y_train)

SVC()

In [ ]:
y_pred = svm.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[18706,   195],
       [ 1256,   843]])

In [ ]:
svc = LinearSVC()
svc.fit(X_train, y_train)

LinearSVC()

In [ ]:
plt.scatter(X_train[:, 0], X_train[:, 1], c=y_train, cmap='winter');
ax = plt.gca()
xlim = ax.get_xlim()
w = svc.coef_[0]
a = -w[0] / w[1]
xx = np.linspace(xlim[0], xlim[1])
yy = a * xx - svc.intercept_[0] / w[1]
plt.plot(xx, yy)
yy = a * xx - (svc.intercept_[0] - 1) / w[1]
plt.plot(xx, yy, 'k--')
yy = a * xx - (svc.intercept_[0] + 1) / w[1]
plt.plot(xx, yy, 'k--')

TypeError: ignored

### Logistics Regression
#### Start with RFE

In [ ]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
rfe = RFE(estimator = logreg, n_features_to_select = 20)
rfe = rfe.fit(X_train, y_train)
print(rfe.support_)
print(rfe.ranking_)

[False False False False False False False False False False False False
 False False False False False False False False False  True False False
  True  True False False False False False False False False False False
  True  True  True False False False False False False False False False
 False False False False False False False False False False False False
 False False  True  True False False False False False False False False
 False False  True  True False  True  True False  True False False False
  True False  True False False  True  True False  True False False False
 False False False False False False False False False False False False
 False False False False False  True False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False  True]
[ 62  43  53  59  34   6  58  54  17  32  26 115  61  65  19  99  51  24
  63  71  10   1  64  75   1   1  91  21  81  14  86  35  50  85  84   4
   1   1   1  20 103  12  18  66  13  98  16  36  29 102 104  22  67   7
  69  56  11  97  52  57  73  72   1   1  23   5  80  27   9  49  48   8
  79  40   1   1  37   1   1  39   1  87  88  28   1  38   1  31  15   1
   1  60   1  94  83  46  55  42  45  25  33   3  44  90   2  92  74  30
  76 111  41  70  47   1 105 109  82  68  78  77  95  96 113 117 121  93
 107 123 131 138  89 130 127 139 143 106 114 122 124 119 120 126 140 141
 100 112 129 116 128 125 142 144 135 147 133 137 101 110 108 118 134 136
 145 149 132 146 148   1]

### Random Forest

In [ ]:
# Import the model we are using
from sklearn.ensemble import RandomForestRegressor
# Instantiate model with 1000 decision trees
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)
# Train the model on training data
rf.fit(X_train, y_train);

In [ ]:
# Use the forest's predict method on the test data
predictions = rf.predict(X_test)
# Calculate the absolute errors
errors = abs(predictions - y_test)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2))